### ISSUE TITLE
Unfixable deprecation warning with rack-timeout integration

### ISSUE THREAD

**Issue by jeremy** [getsentry/raven-ruby#1025]
Using Sentry with rack-timeout now results in a deprecation warning that the wrong file was required.

#1006 got rid of all dasherized filenames. Integrations are automatically loaded based on gem name, however, and rack-timeout is dasherized. So using `rack-timeout` will always require `raven/integrations/rack-timeout`, triggering the deprecation warning.

The workaround is to explicitly specify integrations, omitting rack-timeout, and manually require `raven/integrations/rack_timeout` instead.

I think we should just revert this portion of #1006. Keep the dasherized integration filename that matches the gem name.

**Comment by st0012** [comment]
hey @jeremy, thanks for reporting this issue (and trying out the latest master!). I will fix it today
