### ISSUE TITLE
Idea: Passing lambda to tags_context and extra_context

### ISSUE THREAD

**Issue by gogiel** [getsentry/raven-ruby#131]
It would be nice to have a possibility to pass lambda to tags_context and extra_context to extract some information in runtime.
I think of two scenarios:
* passing lambda that returns Hash instance
* passing lambdas as Hash keys and calling them at runtime

**Comment by nateberkopec** [comment]
Not a lot of action here, so we won't be implementing this. PRs welcome. Somewhat related to #479.

**Comment by ndbroadbent** [comment]
I just had this idea as well. My code currently runs a SQL query to add information about the user and their organization to the `user_context`. It would be great if I could set a lambda so that the SQL query only runs when there's actually an error. (Otherwise it runs on every single request.)
