### ISSUE TITLE
Capture backtrace on Raven.capture_message

### ISSUE THREAD

**Issue by sobrinho** [getsentry/raven-ruby#139]
Hey,

I'm trying to use raven-ruby to capture rails deprecation warnings but I'm not finding a way to pass the backtrace to sentry.

My current approach:

``` ruby
ActiveSupport::Notifications.subscribe('deprecation.rails') do |name, start, finish, id, payload|
  Raven.capture_message(
    "DEPRECATION WARNING: #{payload[:message]}",
    :level => :warning
  )
end
```

Rails provides the `payload[:callstack]` which is the backtrace of the deprecation.

Just the message won't be really useful since I will not be able to trace from where it was triggered.

Suggestions?

_Inspired on @jonleighton approach for honey badger: https://gist.github.com/jonleighton/7122210_

**Comment by NickTomlin** [comment]
I'm looking to do a similar thing and that shared link is currently dead for me. Has anyone been able to do this successfully?

**Comment by irphilli** [comment]
Also looking to do something similar.

**Comment by irphilli** [comment]
In case anyone stumbles upon this, one way to do it is to add the 'backtrace' option like:

```
rescue => e
  Raven.capture_message("Something happened", :backtrace => e.backtrace)
```

**Comment by sobrinho** [comment]
Closing in favor of #766.

**Comment by mltsy** [comment]
@sobrinho - This doesn't seem related to #766 ... they're different things, right?  Capturing the backtrace for messages (this issue) isn't the same as capturing the request body.  Having an option to capture backtrace would still be nice - even though you can kind of do it with `capture_message("message", extra: {backtrace: caller})`

**Comment by mtsmfm** [comment]
It seems we already have backtrace option.

https://github.com/getsentry/raven-ruby/blob/69e0d4bc216d14d7418a3a35e24a00210abeca19/lib/raven/event.rb#L71

So `Raven.capture_message("message", backtrace: caller)` will work

**Comment by mtsmfm** [comment]
Documentation PR already exists https://github.com/getsentry/sentry-docs/pull/766
It's 1 year old PR though

**Comment by mltsy** [comment]
Oooh!  This makes so much more sense!  @sobrinho's closing comment above linked to the wrong # 766 😆 Okay, yup - that's awesome - hopefully someone can merge it...

**Comment by mltsy** [comment]
Fixed! :)
