### ISSUE TITLE
Integrations opt-out

### ISSUE THREAD

**Issue by bobbrez** [getsentry/raven-ruby#217]
Is there any work on enabling integrations to opt-out of being included?
https://github.com/getsentry/raven-ruby/blob/master/lib/raven/base.rb#L200-L206

If not, is there any objection to me submitting a PR?

**Comment by nateberkopec** [comment]
Another idea: don't include raven.

So your Gemfile would look like:

```ruby

gem 'sentry-raven', require: false

```

And in your initialization code:

```ruby
require "raven/base"
require "raven/integrations/rails"
require "raven/integrations/delayed_job"
#etc
```

This stops you from calling Raven.inject, which is where all this integration loading occurs.

**Comment by nateberkopec** [comment]
I think the above is satisfactory. Adding it to our wiki.
