### ISSUE TITLE
View local variables

### ISSUE THREAD

**Issue by ineu** [getsentry/raven-ruby#261]
How do I view local variables when exception happens in Rails? According to https://www.getsentry.com/for/ruby/ is should be possible in Ruby (there's "Expand your scope with context locals" section), but #7 is there for 2.5 years and is not yet closed. So is it not possible? If not, then is it possible to do it manually by using `extra` as described in https://github.com/getsentry/raven-ruby/wiki/Context ?
Thanks in advance.

**Comment by nateberkopec** [comment]
We've fixed the problem on the marketing page. For ongoing discussion of local variable capture, see #7
