### ISSUE TITLE
Encoding::ConverterNotFoundError: code converter not found (US-ASCII to UTF-16)

### ISSUE THREAD

**Issue by shedd** [getsentry/raven-ruby#269]
Saw this exception today from the Raven Ruby library:

```
Error Message:
Encoding::ConverterNotFoundError: code converter not found (US-ASCII to UTF-16)

Where:
[PROJECT_ROOT]/vendor/bundle/ruby/2.1.0/gems/sentry-raven-0.12.2/lib/raven/processor/utf8conversion.rb, line 20
```

**Comment by nateberkopec** [comment]
@shedd can you share the output of ```export $LANG``` for the environment this occurred in?

**Comment by shedd** [comment]
Sure.

This was on Heroku.

```
~ $ export $LANG
bash: export: `en_US.UTF-8': not a valid identifier
```

**Comment by nateberkopec** [comment]
I'm a dummy, I meant `echo`. But thanks! I'm not seeing this on our heroku app, so this isn't env related, probably related to a weird input. Will keep digging! Thanks.

**Comment by nateberkopec** [comment]
Trying my darndest to come up with a reproducing test case but I just can't seem to do it! If anyone else sees this, any help appreciated!

**Comment by DavidDufresne** [comment]
I have also seen this error recently on Heroku.

**Comment by nateberkopec** [comment]
@shedd @DavidDufresne Which version of the heroku stack have you seen this on? Bamboo? Cedar? Cedar-14?

**Comment by DavidDufresne** [comment]
Cedar

**Comment by shedd** [comment]
Cedar-14

We saw this again the other day.

**Comment by nateberkopec** [comment]
Argh. Sorry guys, I'm still in the dark as to what's happening here.

The line in question here is:
https://github.com/getsentry/raven-ruby/blob/master/lib/raven/processor/utf8conversion.rb#L20

Presumably, obj when encoded in US-ASCII won't convert to UTF-16 on Heroku. But the following works just fine for me on a Cedar app:

```
katana:unwindme nateberkopec$ heroku run irb -
Running `irb` attached to terminal... up, run.7501
irb(main):008:0> 'string'.encode("US-ASCII").encode('UTF-16', :invalid => :replace, :undef => :replace, :replace => '').encode('UTF-8')
=> "string"
```

**Comment by shedd** [comment]
@nateberkopec When I've seen this, it's been from a Sidekiq job.

Here's the full backtrace:

```
/vendor/bundle/ruby/2.1.0/gems/sentry-raven-0.12.2/lib/raven/processor/utf8conversion.rb:20 in "encode"
/vendor/bundle/ruby/2.1.0/gems/sentry-raven-0.12.2/lib/raven/processor/utf8conversion.rb:20 in "clean_invalid_utf8_bytes"
/vendor/bundle/ruby/2.1.0/gems/sentry-raven-0.12.2/lib/raven/processor/utf8conversion.rb:10 in "process"
/vendor/bundle/ruby/2.1.0/gems/sentry-raven-0.12.2/lib/raven/processor/utf8conversion.rb:8 in "block in process"
/vendor/bundle/ruby/2.1.0/gems/sentry-raven-0.12.2/lib/raven/processor/utf8conversion.rb:8 in "merge"
/vendor/bundle/ruby/2.1.0/gems/sentry-raven-0.12.2/lib/raven/processor/utf8conversion.rb:8 in "process"
/vendor/bundle/ruby/2.1.0/gems/sentry-raven-0.12.2/lib/raven/client.rb:54 in "block in encode"
/vendor/bundle/ruby/2.1.0/gems/sentry-raven-0.12.2/lib/raven/client.rb:53 in "each"
/vendor/bundle/ruby/2.1.0/gems/sentry-raven-0.12.2/lib/raven/client.rb:53 in "reduce"
/vendor/bundle/ruby/2.1.0/gems/sentry-raven-0.12.2/lib/raven/client.rb:53 in "encode"
/vendor/bundle/ruby/2.1.0/gems/sentry-raven-0.12.2/lib/raven/client.rb:34 in "send"
/vendor/bundle/ruby/2.1.0/gems/sentry-raven-0.12.2/lib/raven/base.rb:71 in "send"
/vendor/bundle/ruby/2.1.0/gems/sentry-raven-0.12.2/lib/raven/base.rb:109 in "block in capture_exception"
/vendor/bundle/ruby/2.1.0/gems/sentry-raven-0.12.2/lib/raven/base.rb:136 in "send_or_skip"
/vendor/bundle/ruby/2.1.0/gems/sentry-raven-0.12.2/lib/raven/base.rb:103 in "capture_exception"
/vendor/bundle/ruby/2.1.0/gems/sentry-raven-0.12.2/lib/raven/integrations/sidekiq.rb:26 in "block (2 levels) in <top (required)>"
/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/exception_handler.rb:20 in "call"
/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/exception_handler.rb:20 in "block in handle_exception"
/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/exception_handler.rb:18 in "each"
/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/exception_handler.rb:18 in "handle_exception"
/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/processor.rb:61 in "rescue in process"
/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/processor.rb:65 in "process"
/vendor/bundle/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26 in "public_send"
/vendor/bundle/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26 in "dispatch"
/vendor/bundle/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:122 in "dispatch"
/vendor/bundle/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:60 in "block in invoke"
/vendor/bundle/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:71 in "block in task"
/vendor/bundle/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:357 in "block in task"
/vendor/bundle/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid/tasks.rb:57 in "block in initialize"
/vendor/bundle/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:15 in "block in create"
```

I have the job params which I'll share with you privately via the email address on your GH profile.

Maybe this will help!  Thanks for investigating this.

**Comment by nateberkopec** [comment]
@DavidDufresne Are you also seeing this error from Sidekiq or some other queueing backend?

I believe that at least for @shedd this may be related to https://github.com/mperham/sidekiq/issues/1597 and https://github.com/redis/redis-rb/issues/421.

**Comment by DavidDufresne** [comment]
I was running a rake task from the Heroku CLI.  I do not believe any queuing was involved.

**Comment by jeanbaptistevilain** [comment]
Hi,
I'm having a similar error in my environment (not Heroku), although the input encoding is ASCII-8BIT in my case : 
`/gems/sentry-raven-0.13.1/lib/raven/processor/utf8conversion.rb:20:in 'encode': code converter not found (ASCII-8BIT to UTF-16) (Encoding::ConverterNotFoundError)`

Dunno if this can help in reproducing the issue...

**Comment by nateberkopec** [comment]
@jeanbaptistevilain Can you describe a little more of the context around that error? I have a (unconfirmed) suspicion that this may have to do with Redis encoding.

**Comment by jeanbaptistevilain** [comment]
I'm getting the error while trying to send a test event after completing the Sentry set up on a Rails 3.2 app. The app runs on a Debian 5.0.10 + Apache / Passenger.
Below is a more complete backtrace.

`xxx@xxx:~/www/xxx$ bundle exec rake raven:test RAILS_ENV=production
** [Raven] Raven 0.13.1 ready to catch errors
Client configuration:
-> server: https://app.getsentry.com
-> project_id: xxxx
-> public_key: xxxxxxxxx
-> secret_key: xxxxxxxxx

Sending a test event:
/gems/gems/sentry-raven-0.13.1/lib/raven/processor/utf8conversion.rb:20:in 'encode': code converter not found (ASCII-8BIT to UTF-16) (Encoding::ConverterNotFoundError)
        from /gems/gems/sentry-raven-0.13.1/lib/raven/processor/utf8conversion.rb:20:in 'clean_invalid_utf8_bytes'
        from /gems/gems/sentry-raven-0.13.1/lib/raven/processor/utf8conversion.rb:10:in 'process'
        from /gems/gems/sentry-raven-0.13.1/lib/raven/processor/utf8conversion.rb:8:in 'block in process'
        from /gems/gems/sentry-raven-0.13.1/lib/raven/processor/utf8conversion.rb:8:in 'merge'
        from /gems/gems/sentry-raven-0.13.1/lib/raven/processor/utf8conversion.rb:8:in 'process'
        from /gems/gems/sentry-raven-0.13.1/lib/raven/client.rb:64:in 'block in encode'
        from /gems/gems/sentry-raven-0.13.1/lib/raven/client.rb:64:in 'each'
        from /gems/gems/sentry-raven-0.13.1/lib/raven/client.rb:64:in 'reduce'
        from /gems/gems/sentry-raven-0.13.1/lib/raven/client.rb:64:in 'encode'
        from /gems/gems/sentry-raven-0.13.1/lib/raven/client.rb:37:in 'send'
        from /gems/gems/sentry-raven-0.13.1/lib/raven/base.rb:83:in 'send'
        from /gems/gems/sentry-raven-0.13.1/lib/raven/base.rb:116:in 'capture_type'
        from /gems/gems/sentry-raven-0.13.1/lib/raven/integrations/rake.rb:9:in 'display_error_message'
        from /gems/gems/rake-10.1.0/lib/rake/application.rb:174:in 'rescue in standard_exception_handling'
        from /gems/gems/rake-10.1.0/lib/rake/application.rb:165:in 'standard_exception_handling'
        from /gems/gems/rake-10.1.0/lib/rake/application.rb:75:in 'run'
        from /gems/gems/rake-10.1.0/bin/rake:33:in '<top (required)>'
        from /gems/bin/rake:19:in 'load'
        from /gems/bin/rake:19:in '<main>'`

Note that the issue cannot be reproduced in my local dev environment (Windows) as the event gets fired properly.
Let me know if I can help, I was actually looking forward to trying Sentry in my production environment.

**Comment by jeanbaptistevilain** [comment]
Just a quick update : upgrading Ruby version from 1.9.2 to 1.9.3 fixed the issue for me.

**Comment by shedd** [comment]
Using a later version of Ruby hasn't helped us - we've been running on Ruby 2.2.2

**Comment by nateberkopec** [comment]
Closing because the issue is stale and is probably environment related anyway - will reopen if anyone can find a repro.
