### ISSUE TITLE
How to serialize Raven::Event?

### ISSUE THREAD

**Issue by marclennox** [getsentry/raven-ruby#282]
I'm trying to use a Sidekiq job to send the raven events, which means I need to serialize the Raven::Event and deserialize it before sending.

I see there's a "to_hash" method but no "from_hash".

I tried to use YAML::load and YAML::dump but it yacks on procs from the config.

Any ideas how I can accomplish this?

**Comment by dcramer** [comment]
Ideally we'd improve the API so you'd just serialize a hash, and the core send() method just took a simple mapping. This is how the Python API works which makes it fairly flexible.

We could do like we do in Python and ensure compatibility by having send(event) => send_remote(hash) and then let you override send_remote or similar.

That said I'm not sure we really need to ensure backwards compat on send

**Comment by marclennox** [comment]
Agreed if I could simply send the hash, this would be ideal.  Is there a work-around with which I can achieve this now?

**Comment by nateberkopec** [comment]
@marclennox Is there any way you could share a gist of the Sidekiq code you use to accomplish this? We need to improve our docs around pushing your Sidekiq sending to a job processor + I want to improve our API around this.

**Comment by marclennox** [comment]
For sure, here you go.

https://gist.github.com/marclennox/b2dc84cc449164ff1397

**Comment by marclennox** [comment]
Note that I'm using ActiveJob with Sidekiq as the provider.

**Comment by nateberkopec** [comment]
ker-pow! addressed by the above.
