### ISSUE TITLE
How do I test if raven is set up and receiving exceptions?

### ISSUE THREAD

**Issue by x-yuri** [getsentry/raven-ruby#284]
I'm mainly concerned about `sinatra` apps here.

**Comment by dcramer** [comment]
It's kind of reasonable to create an endpoint which just causes a 500 so you can test your error handling pipeline. I've done this in the past and had no regrets.

**Comment by nateberkopec** [comment]
@x-yuri It's also very easy in Ruby to do this just in your tests, so you don't have to pollute your app code. For example, in a test you could just reopen a controller and add your test endpoint. I know you're in Sinatra but the principles will be the same:

```ruby
Rails.application.routes.append { "/exception", to: "some#exception" }
class SomeController < ApplicationController
  def exception
    raise "Oh noes!"
  end
end
```

**Comment by x-yuri** [comment]
I should've made that clear, the issue is not with triggering an exception:

```ruby
require 'sinatra'
require 'sentry-raven'
require 'pp'

Raven.configure(true) do |config|
  config.dsn = '...'
end

use Raven::Rack

get '/' do
  'Hello, world!'
end

ENV['RACK_ENV'] = 'test'

require 'rspec'
require 'rack/test'

describe 'app' do
  include Rack::Test::Methods

  def app
    @app || Sinatra::Application
  end

  it 'prints "Hello, world!"' do
    get '/'
    expect(last_response).to be_ok
    expect(last_response.body).to eq('Hello, world!')
  end

  it 'passes errors to Raven' do
    @app = Class.new Sinatra::Application do
      get '/' do
        raise 'something went wrong'
      end
    end
    get '/'
    # what should I expect here?
  end
end
```

**Comment by nateberkopec** [comment]
Testing state here would be tough. Instead, I'd try to make sure that the [#send method was called on Raven::Client](https://github.com/getsentry/raven-ruby/blob/master/lib/raven/client.rb#L25). 

Pseudocode guess:

```ruby
client = Raven.client
client.expects(:send).returns(:true)
```

**Comment by x-yuri** [comment]
Thanks, that must be it. For now I was able to do it only with [`rspec` + `mocha`](https://github.com/rspec/rspec-mocks/issues/874#issuecomment-70826099).

**Comment by x-yuri** [comment]
Okay, that was my fault. I put `ENV['RACK_ENV'] = 'test'` after requiring `sinatra`. So `sinatra` decided it's `development` environment and was intercepting all exceptions. Which prevented `rspec-mocks` from doing its job properly. And this must be it:

```ruby
ENV['RACK_ENV'] = 'test'

require 'sinatra'
require 'sentry-raven'
require 'pp'

Raven.configure(true) do |config|
  config.dsn = '...'
end

use Raven::Rack

get '/' do
  'Hello, world!'
end

require 'rspec'
require 'rack/test'

Raven.configure do |config|
  logger = ::Logger.new(STDOUT)
  logger.level = ::Logger::WARN
  config.logger = logger
end

describe 'app' do
  include Rack::Test::Methods

  def app
    @app || Sinatra::Application
  end

  class TestRavenError < StandardError; end

  it 'passes errors to Raven' do
    @app = Class.new Sinatra::Application do
      get '/' do
        raise TestRavenError
      end
    end
    expect(Raven.client).to receive(:send)
    begin
      get '/'
    rescue TestRavenError
    end
  end
end
```

**Comment by ACPK** [comment]
@x-yuri x-yuri - Any thoughts on creating this as a feature? I was thinking about implementing it, along with an API call to delete the issue from GetSentry.
