### ISSUE TITLE
Stracktrace frames should strip the project_dir from abs_path for filenames

### ISSUE THREAD

**Issue by dannyfallon** [getsentry/raven-ruby#288]
In the [filename method](https://github.com/getsentry/raven-ruby/blob/master/lib/raven/interfaces/stack_trace.rb#L35-L40) you're currently using the $LOAD_PATH array to determine if you can strip the start of the path for the current stacktrace frame. In Rails applications this presents some disadvantages, all related to grouping errors in Sentry

By not including the Rails root or project_dir when attempting to strip prefixes from the absolute path you end up using the full path for errors in places such as views, initialisers etc. This presents a problem if your path contains a variable, for example the timestamp or the SHA for the current version. You essentially end up polluting your sentry list with errors that _should_ be grouped together. Right now we're monkeypatching the filename method to work around this issue

In a bit of a tangent, perhaps using the full $LOAD_PATH is also causing some unintended problems for Rails apps. The Rails autoloader will add some paths such as `/app/models`, `/app/controllers` and `/lib` by default. Imagine a scenario where you've a model named `conversation.rb` and you've a lib of the same name. The filename for an error that happens in either will be the same, so the culprit will be the same. This presents issues in the Sentry UI listing, both errors have the same culprit (`conversation.rb`). It also makes things difficult when viewing the backtrace, which doesn't appear to expose the `abs_path` in an easy way.

**Comment by nateberkopec** [comment]
Related: #278

**Comment by dannyfallon** [comment]
Cheers Nate. We've been running the monkeypatch in production the last few days and it has certainly cleared up the grouping of errors. I'll try submit a PR this week for that behaviour for review

**Comment by nateberkopec** [comment]
@dcramer Can you chime in on what parts of this abs_path issue are something we should solve in the client vs on the Sentry server?

**Comment by dcramer** [comment]
Just to copy convo from IRC:

- absolute path is designed to be the absolute path on disk
- filename is designed to be some kind of normalized or relative path (i.e. you can trim project root)

**Comment by dannyfallon** [comment]
Thanks @dcramer, #278 looks to solve the first issue where the Rails root remains on the filename.

How about your thoughts on the second one? Rails' autoloader adds some directories to the $LOAD_PATH, it might confuse some users by removing valuable path information

**Comment by dcramer** [comment]
Assuming $LOAD_PATH is the same as PYTHONPATH, I think it's fine to only store the full path in abspath and truncate at $LOAD_PATH, but I'm not really sure here.

**Comment by nateberkopec** [comment]
@dannyfallon Is there any way we could produce a "failing test" for your second point?

**Comment by nateberkopec** [comment]
Solved by #278 and #291
