### ISSUE TITLE
Storing Time.now in Rack env Violates the Rack Spec

### ISSUE THREAD

**Issue by pglombardo** [getsentry/raven-ruby#292]
Hi Sentry,

While testing the sentry gem with [one that I maintain](https://github.com/appneta/oboe-ruby), I found that if you also use Rack::Lint, it complains that env contains a non-string value.

![getsentry raven time now 2015-01-27 18 11 11](https://cloud.githubusercontent.com/assets/395132/5922954/f9f6ec50-a64f-11e4-8ade-bdfdede9808f.png)

I tracked the value down to [this line](https://github.com/getsentry/raven-ruby/blob/master/lib/raven/integrations/rack.rb#L50).

The [Rack Spec](http://www.rubydoc.info/github/rack/rack/master/file/SPEC) says "The CGI keys (named without a period) must have String values."  You may be able to get away with this by simply renaming `requested_at` to `sentry.requested_at`.

Sorry this isn't a PR - time is a bit short this week. :-(

**Comment by mattolson** [comment]
Just ran into this as well. I have rack/lint in development.

**Comment by mattolson** [comment]
ping @pglombardo @nateberkopec

**Comment by pglombardo** [comment]
:+1:

**Comment by mattolson** [comment]
Failing on rails 3.2. Working on that now.
