### ISSUE TITLE
Support lambdas for Filter Params

### ISSUE THREAD

**Issue by GeekOnCoffee** [getsentry/raven-ruby#307]
We use a lambda for `Rails.application.config.filter_parameters` so that we can whitelist attributes instead of blacklisting them, but this means we can't pass it into `config.sanitize_fields`. I'm willing to do the work to get a PR put together for this if it's functionality that you're willing to support, though I'm not even completely sure the right direction to start in...

**Comment by nateberkopec** [comment]
I'm still open to doing this, it's just a bit far down on the priority list for me ATM. Happy to look at PRs in this direction.

**Comment by nateberkopec** [comment]
For anyone looking to implement this, here's a little more direction:

* `sanitize_fields=`, inside of Processor::SanitizeData, needs to check if `configuration.sanitize_fields` responds to `call`. If it does, it should `call` and convert the result into an Array. If the result of `call` is not an Array, it should `raise` a Sentry::Error.
* Add some tests describing the above behavior.
