### ISSUE TITLE
Unset DSN doesn't disable Raven

### ISSUE THREAD

**Issue by grega** [getsentry/raven-ruby#308]
As mentioned in the docs; to disable running Raven/Sentry in development I'm setting `config.dsn` to a falsey value. However, whatever value I set appears to either have no effect (using `""` as the DSN I still see `INFO -- : ** [Raven] Raven 0.12.3 ready to catch errors`) or generates an `URI::InvalidURIError` (`false`, `0` or `nil` as the DSN).

Am I missing something blindingly obvious?

Using raven-ruby `0.12.3` and Rails `4.2.0`

**Comment by eugeneius** [comment]
That paragraph in the wiki is wrong. It looks like the author misunderstood [this comment](https://github.com/getsentry/raven-ruby/issues/209#issuecomment-58217021):

> To disable Sentry in a development environment, on any platform, you should set SENTRY_DSN to a falsey value.

That only applies when supplying the DSN as an environment variable. If you're setting `config.dsn` directly, you can avoid sending events by not setting a value at all:

```ruby
Raven.configure do |config|
  config.dsn = "foo" unless Rails.env.development?
end
```

You can also set `config.environments` to only send events to Sentry in certain environments:

```ruby
Raven.configure do |config|
  config.dsn = "foo"
  config.environments = ['staging', 'production']
end
```

I've updated the wiki page to hopefully make this clearer: https://github.com/getsentry/raven-ruby/wiki/Getting-Started#usage

Note that the `Raven 0.12.3 ready to catch errors` message is currently always logged, even if sending is disabled in the current environment. #309 made the log message indicate when sending is disabled, but a new version of the gem including that change hasn't been released yet.

**Comment by grega** [comment]
Thanks @eugeneius, that makes a lot more sense! Will mark this as resolved (and will keep an eye out for the release of the gem that includes #309).
