### ISSUE TITLE
Events not sent in production

### ISSUE THREAD

**Issue by mbajur** [getsentry/raven-ruby#311]
Hello!
I'm in the middle of a process of implementing raven-ruby in my companies rails apps but i have encountered a blocker and i have totally no idea why is that hapenning. 

The thing is - my rails apps are not reporting exceptions. I can run `rake raven:test` and also use `Raven.capture` and they work just fine (on production server and production env) but when some part of my app code throws an exception, raven is not sending any event.

I think it's configured properly cause entering rails console gives me an info about that the Raven is ready to send events but:

```
deploy@server:~/app/current$ bin/rails c
I, [2015-03-27T17:16:39.219527 #17715]  INFO -- : ** [Raven] Raven 0.12.3 ready to catch errors
Loading production environment (Rails 4.1.0)
irb(main):001:0> 1/0
ZeroDivisionError: divided by 0
	from (irb):1:in `/'
	from (irb):1
```

for some reason exepctions are not beeing forwarded.

ruby 2.0.0p598
Rails 4.1.0
ubuntu 14.04 LTS
raven-ruby HEAD

I'm not sure if that's a proper place to send such help request and sorry if it's not. 
Thanks for any help.

**Comment by dcramer** [comment]
The way the automatic exception handling works is via middlewares and other similar hooks. In your case just throwing an exception in irb won't trigger any of that

**Comment by mbajur** [comment]
Oh ok, didn't knew that. Anyway, does raven automatically catch any exceptions during app runtime or i need to somehow implement that on my own? It bothers me because `rake raven:test` task works just fine but, however, one of my api endpoints returns 500 and there are no events recorded in sentry.

**Comment by dcramer** [comment]
I dont think we catch runtime issues (I'm not sure how we could do that, but it might be possible).

I would check your API endpoint to see if its catching the exception. If so the best solution here is to have something like this in your code:

```ruby
def log(exception)
    MyLogger.error('blah blah')
    Raven.captureException(exception)
end
```

And then within your code where you catch and dont re-raise exceptions ensure you log it.

(I dont know Ruby, so sorry for my awful code example)

**Comment by mbajur** [comment]
Ok i think it would be a good idea to describe my short story - previously i was using errbit (which is basicaly an open source clone of airbrake.io). Usage of it is quite simple - you creates an initializer with settings of api key and other airbrake stuff (kind of like /config/initializers/raven.rb) and that's it - if anything will go wrong in your app, the thrown exception is gonna be forwarded to airbrake/errbit, no additional setup needed.

I thought that raven works the same way - i just need to create an initializer with DSN url config and all the unhandled exceptions will be forwarded to my sentry instance. However, it turns out that i need to carry about sending them to sentry on my own using `Raven.captureException` (acording to your last reply).

I'm not saying that it's a bad thing but it would be awesome if anyone could tell me if i'm on point with that or just my rails app is broken :)

Anyway, thanks for your replies @dcramer !

**Comment by dcramer** [comment]
That's actually not true. We install a Rack middleware to capture exceptions. In fact, the raven-ruby gem is modeled off of an older airbrake library.

Did errbit capture the exception in this same situation?

**Comment by mbajur** [comment]
Yes. For testing/staging purposes, i currently have errbit and raven installed simultaneously and the exception we're talking about is beeing forwarded to errbit/airbrake but not to sentry.

**Comment by dcramer** [comment]
Are you doing anything beyond setting the API key/DSN/equivalent in your initializers (for both errbit and raven)?

This definitely sounds like either a bug on our end or something we should be implementing.

**Comment by mbajur** [comment]
Nope, just the basic stuff. I'm gonna prepare a dummy rails app tomorrow to make debugging easier.

**Comment by mbajur** [comment]
Ok, problem solved. I realized that this exception actually is handled by kind of a json serializer (it was raised in json api) and changing the way of handling exceptions in my whole app solved it. Thanks for your support dcramer and sorry for me being an idiot :)
