### ISSUE TITLE
Why not release a new version?

### ISSUE THREAD

**Issue by eagletmt** [getsentry/raven-ruby#313]
The latest gem version is v0.12.3, which was relased on 2015-01-16.
There are several bug fixes and enhancements since v0.12.3.
https://github.com/getsentry/raven-ruby/compare/0.12.3...master

Why not release a new version? Any blockers?

**Comment by nateberkopec** [comment]
Nope, I'll wrap one up today.

**Comment by eagletmt** [comment]
Good! I'm looking forward to the next release :yum:

**Comment by nateberkopec** [comment]
https://github.com/getsentry/raven-ruby/commit/20c5d92b2b1327afa181f913cdbbd44b861fdd00
