### ISSUE TITLE
allow using SanitizeData without credit card filtering

### ISSUE THREAD

**Issue by codekitchen** [getsentry/raven-ruby#328]
One of our applications uses a somewhat unusual sharding scheme, and account ids end up matching the `CREDIT_CARD_RE` defined in `SanitizeData`. We'd still like to use the other parameter filtering, but right now we have to disable it completely to get those ids across in the event information.

I can see a couple different solutions, either a config param on SanitizeData, or perhaps splitting it up into two separate processors, one that does key-based filtering and one that filters on the credit card regex. Do either of those sound like a good approach?

Of course, we had to turn off all sanitization server-side for this project as well, but that's a separate issue.

**Comment by nateberkopec** [comment]
Either of those approaches sound perfectly fine.

**Comment by codekitchen** [comment]
PR opened
