### ISSUE TITLE
Default excluded exceptions and explicit excluded exceptions are ignored

### ISSUE THREAD

**Issue by gregkare** [getsentry/raven-ruby#336]
I have the same issue when using the default list of excluded exceptions and passing them explicitly: exceptions are still sent to Sentry.

Here's the list I'm using right now in a Rails app (after realising the default list did not work):

```ruby
config.excluded_exceptions = [
  'ActionController::RoutingError',
  'Mongoid::Errors::DocumentNotFound'
]
```

This looks similar to #27, looks like it either never worked or that it's a regression.

**Comment by nateberkopec** [comment]
That's strange, the default list has always worked for me. Can you give me some more details here?

**Comment by gregkare** [comment]
I can't reproduce the problem anymore, closing.
