### ISSUE TITLE
Reporting NaN & Infinity values

### ISSUE THREAD

**Issue by Alric** [getsentry/raven-ruby#340]
An error occurs if you specify extra data including NaN or Infinity. I'm wondering if that's the right decision.

For example:
` Raven.capture_message('NaN test', extra: { unexpected: 0/0.0} )` =>  "Raven::OkJson::Error: Numeric cannot be represented: NaN"  
` Raven.capture_message('Infinity test', extra: { unexpected: 1/0.0} )` =>  "Raven::OkJson::Error: Numeric cannot be represented: Infinity"

That's clearly coming out of the `numenc` method in okjson.
https://github.com/getsentry/raven-ruby/blob/master/lib/raven/okjson.rb#L500

The decision to reject these invalid numerics seems reasonable to me in a general purpose encoder. However, in the context of trying to serialize information for error reporting, I'm not so sure. 

This is the specific scenario I encountered:
  0. You have a NaN value in a field where you weren't expecting it.
  0. It causes an error in app logic.
  0. You have a rescue block around this part of the code, to add debugging data if an error occurs.
  0. You rescue the error and try to log with capture_exception, passing in the extra data.
  0. The NaN in your extra data causes this error in OkJson.
  0. This makes your original app logic error never be reported, though this NaN error will probably be reported – depending on your setup, I guess.

I'm accustomed to being careful with unexpected nils when building extra debugging data. I'm not accustomed to checking numerics for finite?, and I don't think users of the library should have to be.

I can see some arguments for this behavior, both theoretical and practical, but I mainly wanted to be sure this behavior was purposeful – and not just an accidental consequence of using okjson. 

And secondarily, I wanted to see if you had any thoughts on making this behavior at least configurable. I'd personally just prefer them encoded as strings. As gnarly as that is, at least it won't interfere with capturing the exception. Thanks!

**Comment by nateberkopec** [comment]
> I can see some arguments for this behavior, both theoretical and practical, but I mainly wanted to be sure this behavior was purposeful – and not just an accidental consequence of using okjson.

This behavior is purposeful only in that it's what you would expect from a strictly spec-follow JSON parser.

> The decision to reject these invalid numerics seems reasonable to me in a general purpose encoder. However, in the context of trying to serialize information for error reporting, I'm not so sure.

I think this is valid. This is the reason why we vendored OKJson, so we can do weird, non-JSON-spec-compatible stuff when the use case warrants.

I'm in favor of encoding NaN and +/- Infinity as strings in our OKJson. PR's welcome to that effect. 

> And secondarily, I wanted to see if you had any thoughts on making this behavior at least configurable. I'd personally just prefer them encoded as strings. As gnarly as that is, at least it won't interfere with capturing the exception. Thanks!

I would prefer not to add a configuration point. We have too many as it is, and I can't see why anyone would *want* Sentry to throw an exception in this case.

**Comment by Alric** [comment]
:+1: I'll try to put a PR together. It should be straightforward, I think, just need to resolve the original issue in my app that highlighted this to begin with. Thanks for the prompt reply.
