### ISSUE TITLE
Raven not sanitizing query string parameters

### ISSUE THREAD

**Issue by Timo614** [getsentry/raven-ruby#341]
I just stepped through this locally and found that this line never returns true:
https://github.com/getsentry/raven-ruby/blob/master/lib/raven/processor/sanitizedata.rb#L26

The reason this is happening is because `k == :query_string` not `k == "query_string"` it appears at least locally when I'm running this.

To test what was happening I monkey patched into that module and inspected the result of `process` when my filtered parameter was in the response. I noticed that even the parameter `password` I had added (one which is in the default parameters) appears to be in plaintext when it's done filtering. Inspecting that line and then switching it to a symbol fixed the issue for me locally.

An aside: I'd wager there's some additional filtering being done on sentry's side for any parameters which slip through? I did notice password is filtered in the listed querystring on an error on my sentry dashboard despite the fact the sanitization didn't work. Also a random parameter is sanitized `fanclub_api_key` but I don't have `key` `api_key` etc in my filtered list. Is that intentional? Not clear from the gem where that filtering occurs.

**Comment by nateberkopec** [comment]
> I'd wager there's some additional filtering being done on sentry's side for any parameters which slip through?

Yes, there is.

> Also a random parameter is sanitized fanclub_api_key but I don't have key api_key etc in my filtered list. Is that intentional?

That's correct - [this is also something filtered on the Sentry server](https://github.com/getsentry/sentry/blob/68a30d95644295af1aa077aa6d04c183309b5743/src/sentry/constants.py#L228). We should probably add that to our list as well.

**Comment by nateberkopec** [comment]
Which version of the gem are you using, and are you using the default processors?

**Comment by Timo614** [comment]
Hey Nate, using 0.13.0 but it looks like 0.13.3 has the same code here:
https://github.com/getsentry/raven-ruby/blob/0.13.3/lib/raven/processor/sanitizedata.rb#L26

Using the default processors. I was actually looking into why `fanclub_api_key` was getting sanitized when I noticed that my query string locally wasn't getting sanitized at all. I stepped through and then noticed that the key for the query string field for me was a symbol which was why it wasn't decoding the parameters and running them through. Once I did switch it to a symbol on my machine then `fanclub_api_key` wasn't sanitized (because as you mentioned that was a server only one) but password was (where it wasn't prior to my change locally).

**Comment by jason-o-matic** [comment]
I've been running into this for awhile and was adding "query_string" to `sanitize_fields` to prevent data leakage. Unfortunately this meant I didn't capture other query params that were useful for debugging.

https://github.com/getsentry/raven-ruby/pull/349 updates the sanitization so `:query_string` the symbol gets handled as well.
