### ISSUE TITLE
Config option for blacklisting environments

### ISSUE THREAD

**Issue by mehulkar** [getsentry/raven-ruby#342]
We have the use case of not knowing the name of the environments that our customer will use, so we can't create an explicit whitelist. But we definitely don't want to send exceptions in test and development environments. It would be nice to allow the `send_in_current_environment?` to check a blacklist as well as a whitelist.

**Comment by nateberkopec** [comment]
Hm, could you perhaps utilize the `should_capture` option? https://github.com/getsentry/raven-ruby/wiki/Advanced-Configuration#excluding-exceptions

**Comment by mehulkar** [comment]
Possibly. But it seems like the wrong use case for `should_capture`? It's also one thing to block notifications individually, versus globally turn off raven. E.g. when I initialize Rails, the logger should still tell me that Raven will not send notifications (like it does when the whitelist criteria is not met)

**Comment by nateberkopec** [comment]
> E.g. when I initialize Rails, the logger should still tell me that Raven will not send notifications (like it does when the whitelist criteria is not met)

That's true. I guess I'm just loathe to add yet another config knob here. Having a blacklist *and* a whitelist seems excessive to me. I'm not sure how common your use case really is, and it is, strictly speaking, accomplishable via `should_capture`, or, worst-case, a monkey patch over `send_in_current_environment?`

**Comment by mehulkar** [comment]
Fair enough. `should_capture` seems to be for individual exception types rather than global turn on and off, which makes sense to me. I wouldn't want to be checking `Rails.env` in there. 

Couple other options:

- expose `send_in_current_environment?` as a configurable Proc or something which defaults to `true`. Then you reduce the dependency on the environment name and also ax 2 config knobs! :smile: 
- let `send_in_current_environment?` fallback to an environment variable
- allow a .yml config file to read options from and let users configure as they wish per machine. 

FWIW, [Travis CI uses][1] the whitelist/blacklist approach as well. 

[1]: http://docs.travis-ci.com/user/build-configuration/#White--or-blacklisting-branches.

PS, continuing this for the sake of discussion. I don't think this is a showstopper for us, so if you don't think any of the proposed solutions or if the problem isn't large enough to merit a change, feel free to close this issue. I can submit a patch if you are interested in pursuing though!

**Comment by naw** [comment]
Rather than having a whitelist and a blacklist for named environments, it would be better to have neither.

Just have a boolean configuration option `enabled` and let app developers turn it on or off depending on their own app-specific configuration (i.e. `ENV`, YAML files, etc.)   There is no reason for this gem to know anything about `Rails.env`.

**Comment by naw** [comment]
To be clear, I'm thinking Raven is enabled by default, but a developer could write an initializer like this:

```
Raven.configure do |config|
  config.enabled = false if some_condition_based_on_my_app_specific_config_goes_here
end
```

**Comment by naw** [comment]
So for the use case @mehulkar described, you _could_ write something like this:

```
Raven.configure do |config|
  config.enabled = !(Rails.env.test? || Rails.env.development?)
end
```

Or, if you subscribe to the thinking here: http://12factor.net/config, you could do something more like this:

```
Raven.configure do |config|
  config.enabled = ENV["USE_SENTRY"] == "yes"
end
```

**Comment by mehulkar** [comment]
Yes, this approach would be great for me.

**Comment by nateberkopec** [comment]
:+1: Worth noting also that you could just that the SENTRY_DSN env variable also works for this purpose - not setting it and not explicitly enabling Raven *should* disable Raven.

**Comment by naw** [comment]
Thanks for mentioning that you can simply not set SENTRY_DSN.   I guess that didn't occur to me even though it's right in the README.  So definitely an explicit `enabled` flag isn't really necessary then.

I'd vote for removing the environments array altogether, but I suppose that wouldn't be very backward compatible.

**Comment by nateberkopec** [comment]
Correct. And I don't have a very good deprecation policy yet. Soon ™!
