### ISSUE TITLE
should not send exceptions if environments array is empty

### ISSUE THREAD

**Issue by naw** [getsentry/raven-ruby#347]
Release 0.13.2 introduced a subtle change in how an empty environments array affects whether exceptions are sent to sentry. Formerly an empty array would not send exceptions, but bf52c12dbb14068ac48c384203998337f37a5a07 changed it such that an empty array is the default and is interpreted as sending in all environments.

See https://github.com/getsentry/raven-ruby/commit/bf52c12dbb14068ac48c384203998337f37a5a07#commitcomment-11838256 for the initial discussion

For this particular issue, my recommendation is the environments array default to contain the current environment, and then interpret an empty array as sending in _no_ environments instead of _all_ environments.

However, in the long run I think using a whitelist for environments is a bit of an anti-pattern, and I'll comment on that more in #342

**Comment by nateberkopec** [comment]
Thanks. 

Re: your second comment, we don't recommend using the env array anymore, and instead use the SENTRY_DSN env variable: https://github.com/getsentry/raven-ruby/wiki/Advanced-Configuration#environments

**Comment by nateberkopec** [comment]
Closing this - just use `SENTRY_DSN`.
