### ISSUE TITLE
Unable to load raven/integrations/railties

### ISSUE THREAD

**Issue by peddinti** [getsentry/raven-ruby#350]
Hi i am getting the following error when trying to load my server

* [Raven] Unable to load raven/integrations/railties: undefined method `runner' for #<Raven::Rails:0x007fa4bac864f8>

any idea why?

**Comment by nateberkopec** [comment]
Rails version and Ruby version?

**Comment by peddinti** [comment]
rails 3.2.13 and ruby: 2.2.2p95

**Comment by chrkau** [comment]
I just fixed the same bug in a legacy Rails 3.0 app. It problem wasn't actually the warning about the runner method not existing. I had put raven.rb in the wrong place (yay typo!). Perhaps that is/was the problem here, too.

**Comment by mjdavies** [comment]
I'm seeing the same issue here, rails 3.2.11 and ruby:2.2.2p95

I'm going to try upgrading the rails to the highest rails3.2 I can get away with without blowing the app

**Comment by jlehman** [comment]
I have this problem as well in an order Rails app, but can't seem to work out a fix:

Rails 3.1.10
ruby 2.1.2p95
