### ISSUE TITLE
Logging errors in development

### ISSUE THREAD

**Issue by tonywok** [getsentry/raven-ruby#359]
Sentry does a nice job combing nested exceptions via `cause` in ruby 2.1+. I was wondering if it's possible to log the sentry event, but not actually send it.

In other words, I want to see the nested exception stack trace in my rails log, but I don't want to clutter sentry with errors from developer machines.

Is this supported? If so, how? Apologies if this is obvious, I wasn't able to get it working using the logging options. I just upgraded from 0.12 to 0.14 - perhaps there is lingering configuration somewhere I didn't account for.

Thanks!

**Comment by dcramer** [comment]
Are you talking about having raven-ruby act as the logger? If so it's a bit outside of the scope of the project. If you want to log things + capture them I'd suggest abstracting something like logException() and have it do both there.

**Comment by tonywok** [comment]
@dcramer In development I'd just like to log them. Mostly so I can have [this](https://github.com/getsentry/raven-ruby/blob/3f890829973dba6be542c16d6b5357be38215c5d/lib/raven/event.rb#L168) behavior visible in dev.

Is that out of scope? Thanks for the quick reply btw.

**Comment by dcramer** [comment]
I assume thats primarily because Ruby doesnt do something reasonable by default? I definitely think raven-ruby acting as the logger for error catching is out of scope. Ideally there would be a logging package that does everything, and it also can handle sending the errors to Sentry.

**Comment by tonywok** [comment]
@dcramer Yeah, exactly. The exception instance has a `cause` but it isn't logged. Raven does a way better job, ha.
