### ISSUE TITLE
Rubocop

### ISSUE THREAD

**Issue by alyssa** [getsentry/raven-ruby#362]

**Comment by dcramer** [comment]
I'm a big fan of more automated checks to enforce standards/stability, but I'm also not a Rubyist so would defer to @nateberkopec and others.

**Comment by nateberkopec** [comment]
Oh neat, I thought @dcramer would be mad that we'll force him to stop writing Python-flavored Ruby ;)

I'm generally _for_ rubocop, but the initial config is important. A rubocop config that's super restrictive from the getgo doesn't help anyone. Let's initially commit a config which doesn't raise any errors, then go from there. 

Also, adding it to the CI would be good.

**Comment by ddrmanxbxfr** [comment]
I gave it a spin pretty quickly.

The current offences are currently ignored.

We could open a meta issue, to reference the code styling nits from there.

**Comment by nateberkopec** [comment]
Closed by #391!
