### ISSUE TITLE
Add logged in user to exceptions

### ISSUE THREAD

**Issue by sobrinho** [getsentry/raven-ruby#363]
Reading [here](https://github.com/getsentry/raven-ruby/wiki/Context) it says to "Set some context via a middleware" but do not show how.

Are we supposed to do that (in case of rails)?

``` ruby
class ApplicationController
  before_filter :set_raven_context

  protected

  def set_raven_context
    Raven.user_context id: current_user.id, email: current_user.email
  end
end
```

**Comment by dcramer** [comment]
@sobrinho we're not Rails users ourselves, but generally middleware would probably refer to Rack middleware. You can see an example in how you might do this via our HTTP context layer:

https://github.com/getsentry/raven-ruby/blob/master/lib/raven/integrations/rack.rb
