### ISSUE TITLE
Resque support

### ISSUE THREAD

**Issue by tonywok** [getsentry/raven-ruby#364]
Hey there, thanks for taking the time to look at my issue.

Our app uses the latest raven-ruby (atm 0.14.0) resque (1.25.2) and rails (4.2.3). In an attempt to modernize our rails stack, we've switched to active job, which I see raven-ruby supports via an "integration". However, the active job integration just prints out the job's class name - which isn't too useful. That said, I see why that's all it can guarantee, given that the different active job queue adapters have varying APIs.

Prior to upgrading raven we were using the https://github.com/gocardless/resque-sentry gem. We're still using it, and it works fine for resque jobs. However, for active job's it doesn't trigger any more, causing us to lose helpful debugging information.

I've noticed that raven-ruby supports a sidekiq integration, and actually has a condition to skip if sidekiq in the active job integration here: https://github.com/getsentry/raven-ruby/blob/master/lib/raven/integrations/rails/active_job.rb#L9

While it's entirely possible that we may switch to sidekiq at some point in the future, in order to do that without stopping the world we'd have to get behind the active job abstraction. Using active job without helpful debugging isn't an option for us, so I've come up with a simple work around:

```ruby
# in config/initializers/raven.rb
module Raven
  class Rails < ::Rails::Railtie
    initializer 'raven.active_job' do
      # noop for now, continue to use resque-sentry
    end
  end
end
```
Would you be willing to officially support resque? I'd prefer to not have to monkey patch. If so, I'd be happy to submit a PR. In the meantime, I'm looking through the active_job interface to see if there is a interface supported way to get the arguments to the job across queue adapters so that I can send them off to sentry for better default debugging.

Thanks again for your time.

**Comment by tonywok** [comment]
Turns out active_job does have a decent interface across queue adapters. See here: https://github.com/rails/rails/blob/7a3ca69959e312a215d5e8144fca79a08654fd89/activejob/lib/active_job/core.rb#L7

**Comment by nateberkopec** [comment]
The long term plan is to ship with only an active_job integration, and people can ship a `raven-ruby-sidekiq` gem if they don't want to use AJ. So adding a specific resque integration into this repo is not the plan. 

As for monkey patching - the only thing that needs to be changed here is how `inject` works: https://github.com/getsentry/raven-ruby/blob/master/lib/raven/base.rb#L206. We need to be loading available integrations dynamically. Then you should be able to add your own integrations modules.

I think this clarification plus #365 solves this issue.
