### ISSUE TITLE
async Raven.send_event not thread safe with rack

### ISSUE THREAD

**Issue by sunkencity** [getsentry/raven-ruby#366]
from docs:

```
Raven.configure do |config|
  config.async = lambda { |event|
    Thread.new { Raven.send_event(event) }
  }
end
```

not thread safe.

```
raven-ruby/lib/raven/interfaces/http.rb

      self.data =
        if req.form_data?
          req.POST
        elsif req.body
          data = req.body.read # <-- here  IOError in Rack application object (not opened for reading)
          req.body.rewind
          data
        end
```

**Comment by sunkencity** [comment]
capture state directly then send?

**Comment by nateberkopec** [comment]
Good catch. This should be fairly easy to write a failing spec for. I'm not positive of what the right solution should be.

**Comment by sunkencity** [comment]
Ideally I think there would be a way to just put the delivery of the error in a thread.
Raven.capture_exception_state(e).deliver_later()

**Comment by nateberkopec** [comment]
I've been thinking about that division for a while.

Ideally, the only thing that gets "async'd" is delivery, not capture. Unfortunately, those two concerns are not entirely separated in the code right now, making this very difficult.

**Comment by sunkencity** [comment]
what would be the problem with adding it to the transport layer something like this (just quick untested code, could be written better)

```ruby
#file lib/raven/transports/http.rb
    class HTTP < Transport
      def send_event(auth_header, data, options = {})
        project_id = self.configuration[:project_id]
        path = self.configuration[:path] + "/"
        url = "#{path}api/#{project_id}/store/"
        content_type = options[:content_type]

        if self.configuration[:deliver_sync]
          response = conn.send(url) do
            req.headers['Content-Type'] = content_type
            req.headers['X-Sentry-Auth'] = auth_header
            req.body = data
          end
        else
          a_conn = new_conn
          Thread.new do
            begin
              a_conn.send(url) do
                req.headers['Content-Type'] = content_type
                req.headers['X-Sentry-Auth'] = auth_header
                req.body = data
              end
            rescue => e # must never throw? 
              Raven.logger.warn "Error sending async #{e.inspect}"
            end
          end
          response = true # or what is needed?
        end

        Raven.logger.warn "Error from Sentry server (#{response.status}): #{response.body}" unless response.status == 200
        response
      end

      def conn
        @conn || self.new_conn
      end

      def new_conn
        self.verify_configuration
        ...
```

**Comment by sunkencity** [comment]
it would require some kind of limit of threads (1?) I suppose.

**Comment by giedriusr** [comment]
>Ideally I think there would be a way to just put the delivery of the error in a thread.
Raven.capture_exception_state(e).deliver_later()

:+1:

**Comment by nateberkopec** [comment]
> Ideally I think there would be a way to just put the delivery of the error in a thread.

To be clear, this is exactly what `config.async` is *supposed* to be for. It doesn't work because we haven't cleanly separated delivery from capture.

**Comment by nateberkopec** [comment]
[Check out my spec here.](https://github.com/nateberkopec/raven-ruby/commit/a8cbf4ede4a998f6c0102747befc0e10503bf6be) It passes on MRI and JRuby.

**Comment by nateberkopec** [comment]
Closing until I get a repro.
