### ISSUE TITLE
Grape API - Raven

### ISSUE THREAD

**Issue by steverob** [getsentry/raven-ruby#373]
Hi Im using Grape API https://github.com/ruby-grape/grape. How do I configure raven to send exceptions happening in Grape? Thanks.

**Comment by mjdavies** [comment]
Hi Steve

What have you tried so far?

Matt

**Comment by nateberkopec** [comment]
@steverob Are you using Grape standalone as a Rack app, or as part of a Rails app or Sinatra app?

**Comment by steverob** [comment]
Using it in a Rails app :)

--
Regards
Steve Robinson

**Comment by reneklacan** [comment]
@nateberkopec any answer please? I am using Grape inside of Rails too and I would like to setup Sentry just for the Grape part without affecting Rails at all ... is it possible?

**Comment by nateberkopec** [comment]
Try this:

In your Gemfile:

```
gem 'sentry-raven', require: 'sentry-raven-without-integrations'
```

Then in your Grape controller:

```
require 'raven/integrations/rack'

class API < Grape::API
  use Raven::Rack
end
```

**Comment by constantm** [comment]
For anybody getting to this issue in 2023, the way I get Sentry with with Grape. Set up as normal for rest of Rails app, and in your Grape API root:

```ruby

require 'sentry-ruby'

class API < Grape::API
  use Sentry::Rack::CaptureExceptions

  content_type :json, 'application/json'

  prefix 'api'
  format :json

  rescue_from :all do |e|
    Sentry.capture_exception(e)
    error!('Internal server error', 500)
  end

  # The rest of your API stuff
end

```
