### ISSUE TITLE
SignalException not excluded despite being in excluded_exceptions

### ISSUE THREAD

**Issue by drn** [getsentry/raven-ruby#382]
Hello,

A few of our rails apps are still seeing `SignalException`s on our dashboard. We'd like to exclude these exceptions from our dashboard since they're caused by Heroku restarts.

We have the following in the raven initializer:
```
Raven.configure do |config|
  ...
  # exclude exceptions
  config.excluded_exceptions = [
    'SignalException' # Heroku dyno restarts
  ]
end
```

However, the exceptions are still showing up:
```
SignalException: SIGTERM
Error | polyglot.rb in require at line 65 | rake
```

Thoughts? Thanks!

**Comment by drn** [comment]
I did some digging and wrote a test to verify `SignalException`s are captured. The specs (as written) actually passed - https://github.com/getsentry/raven-ruby/commit/8a38a39b95deaab3dbbb29fa8774625011c7121e . However, we still see these exceptions coming in during Heroku server restarts.

As I listed above, our initializer is `config/initializers/sentry_raven.rb`:
```
Raven.configure do |config|
  ...
  config.excluded_exceptions = [
    'SignalException' # Heroku dyno restarts
  ]
  ...
end
```

However, looking into it, it looks like these exceptions are only coming through in `rake` tasks. Could it be possible that exceptions aren't being properly excluded in rake tasks? I am pretty sure that the environment (and initializers) are loaded when these rake tasks are run.

Cheers!

**Comment by nateberkopec** [comment]
@drn it looks like the SignalException is being raised while files are being `require`d, which leads me to believe your configuration has not yet been loaded. I would suggest the following:

```ruby
# Gemfile
gem 'raven-ruby', require: false
```

```ruby
# config/initializers/sentry_raven.rb
require 'raven-ruby'

Raven.configure do |config|
  ...
  config.excluded_exceptions = [
    'SignalException' # Heroku dyno restarts
  ]
  ...
end
```

There's still a chance that you'll catch a SignalException if it occurs between requiring Raven and executing the config block.

In addition, you will no longer catch any other exceptions raised before the initializer is executed.

**Comment by drn** [comment]
Perfect. I'll test this out next week and will let you know if the SignalExceptions are suppressed. Thanks!

**Comment by drn** [comment]
Your solution worked perfectly for our purposes. Thanks for the help

**Comment by nateberkopec** [comment]
Cheers mate :)
