### ISSUE TITLE
including params and session data

### ISSUE THREAD

**Issue by chadwtaylor** [getsentry/raven-ruby#387]
Coming here from Airbrake and the `params` and `session` data are very important especially for debugging purposes. Been googling and reading the docs, not getting any leads on how to get those included automatically.

Any tips and guidances are greatly appreciated.

**Comment by iloveitaly** [comment]
@chadwtaylor here's a snippet that's working well for me. `admin` is my devise user model.

```ruby
class ApplicationController < ActionController::Base
  before_action :set_raven_context

  def set_raven_context
    if admin_signed_in?
      Raven.user_context({
        user_id: current_admin.id,
        email: current_admin.email,
      })
    end

    Raven.extra_context(
      params: params.to_hash,
      controller: params[:controller],
      action: params[:action],
      url: request.url
    )
  end
end
```

**Comment by iloveitaly** [comment]
Note that `params.to_hash` needs to be `params.to_unsafe_h` in rails5.
