### ISSUE TITLE
Raven shouldn't raise an exception on improperly encoded data

### ISSUE THREAD

**Issue by jason-o-matic** [getsentry/raven-ruby#389]
I can see an argument for "fail fast" as well, but just in case you want to add some extra error handling I ran into this issue:

```
[13] pry(main)> Raven.capture_exception(Exception.new("GIF89a\u0001\u0000\u0001\u0000\x80\xFF\u0000\xFF\xFF\xFF\u0000\u0000\u0000,\u0000\u0000\u0000\u0000\u0001\u0000\u0001\u0000\u0000\u0002\u0002D\u0001\u0000;"))
ArgumentError: invalid byte sequence in UTF-8
from /data/docraptor/shared/bundle/ruby/2.2.0/gems/sentry-raven-0.13.3/lib/raven/processor/sanitizedata.rb:31:in `match'
```

The string is gif data, but as written the string ends up having a UTF8 encoding. This means `gif =~ /asdf/` raises an exception. It might be worth updating the sanitizer to handle this. Perhaps the sanitizer could replace this value with a dummy string saying the original string had a bad encoding, or could force a binary encoding.

**Comment by nateberkopec** [comment]
I'm not sure what we can do about this, since it's raising an ArgumentError - not something we can easily deal with.

Maybe you could rewrite your code to something like:

```
begin
  gif =~ /asdf/
rescue ArgumentError
  #in this context, this is probably an encoding problem
  raise "Bad encoding!" # or whatever
end
```

**Comment by nateberkopec** [comment]
I guess we could make the sanitizer swallow exceptions that contain "invalid byte sequence" in their messages, but that feels extremely jank.

**Comment by nateberkopec** [comment]
Oh, now I see - the problem is how an Exception object is treated by our UTF-8 processor. We correctly clean simple primitives, but not Exceptions. That should be easier to fix.

**Comment by nateberkopec** [comment]
@jason-o-matic Take a look at #426

**Comment by jason-o-matic** [comment]
Seems reasonable, but why the `begin`/`rescue`? Why not just make `clean_exc` from `value`?

**Comment by nateberkopec** [comment]
Oh yeah, duh!
