### ISSUE TITLE
Test against an actual Rails app

### ISSUE THREAD

**Issue by nateberkopec** [getsentry/raven-ruby#417]
We're never going to make progress on these Rails issues if our test suite doesn't cover actually catching Exceptions in a running Rails app.

**Comment by iloveitaly** [comment]
I had to the same thing for a gem I was working on and found some code and modified some code from ThoughtBot to create a rails app within my test suite to test against.

Wanted to pass this along in case it's helpful: https://github.com/NetSweet/netsuite_rails/blob/master/spec/support/test_application.rb

**Comment by nateberkopec** [comment]
Thanks! Did something pretty similar in cd2f174e6c50
