### ISSUE TITLE
Delayed job extra info truncated because of last_error

### ISSUE THREAD

**Issue by claytron** [getsentry/raven-ruby#434]
There was a recent change to limit the `handler` for delayed jobs extra info. This works, but there is also the `last_error` field which can be very large (it is a full stack trace). Can this field be limited in a similar manner so that the rest of the delayed job info shows up?

**Comment by nateberkopec** [comment]
Yup. [Can you open a PR based on this one](https://github.com/getsentry/raven-ruby/commit/5fd53382e15efe46f5144162f532908f07d83c0d#diff-749f3f297c45f664e45645c19beb81f3)? Set a sane limit on the characters based on your experience as a DelayedJob user.
