### ISSUE TITLE
Drop 1.8.7 support

### ISSUE THREAD

**Issue by nateberkopec** [getsentry/raven-ruby#442]
It's time (maybe). Surveys peg 1.8.7 usage at 1% of active applications, and has been EOL for years now. It's the most pain to maintain (I can't even compile it right now).

I'm willing keep 1.9 for now, we don't nearly have to do the same amount of work and backporting to support it.

**Comment by nateberkopec** [comment]
Going for it, since no one commented here. Will include a version bump.

**Comment by seanlinsley** [comment]
As of a year ago today (what a coincidence) Ruby 1.9.3 is no longer supported: https://www.ruby-lang.org/en/news/2015/02/23/support-for-ruby-1-9-3-has-ended/

**Comment by nateberkopec** [comment]
Closed by #465.

Worth noting 2.0.0 went EOL today. TBH there's very little work involved in supporting 1.9 and 2.0 so I'm not worried about dropping those at this time.
