### ISSUE TITLE
Leaking session cookies?!

### ISSUE THREAD

**Issue by jarmo** [getsentry/raven-ruby#445]
I've tried to add `sentry` to my `Rails` app and tested it out in `development` environment. For my surprise I saw my session cookie (with value) on sentry's web interface.

I tried to find cookie-specific code or issue, but did not find any - it seems that all headers/cookies are sent.

[Only issue](https://github.com/getsentry/raven-ruby/issues/253) I found was pointing to a non-existing wiki page.

Sentry **should not ever** send out session cookies, but it seems that this is currently the case.

I'm using `sentry` from `master`.

**Comment by nateberkopec** [comment]
> Sentry should not ever send out session cookies, but it seems that this is currently the case.

Sentry's current positon is that we send cookies by default. Filtering session cookies out from this is sort of difficult with the current processor infrastructure, but not impossible. We should probably add processors to the pipeline if using Rails or Rack that deal with common session cookies and filter them out.

**Comment by jarmo** [comment]
Since sentry has an integration for Rails, then discovering session cookie should not be that difficult. Of course it depends how many Rails versions are officially supported etc.

**Comment by nateberkopec** [comment]
Leaving this open because I want to add an optional SessionCookie processor.

**Comment by nateberkopec** [comment]
Changed my mind. If you want to send cookies but *not* send session cookies, write your own processor based on the Cookies one.

**Comment by jarmo** [comment]
Went "unsecure by default" route? That's bad :-1:

**Comment by nateberkopec** [comment]
No cookies are sent at all by default.

**Comment by jarmo** [comment]
That's even better :) This information was not included in here before. Thanks!
