### ISSUE TITLE
Raven.capture_release?

### ISSUE THREAD

**Issue by mllocs** [getsentry/raven-ruby#446]
I wonder how can we capture the release context with the latest update. I would expect something like Raven.capture_release but it doesn't exist. 

Should we pass it as a tag?

```ruby
Raven.capture_context release: '1.2.3'
```

Or as a config param:

```ruby
Raven.configure do |config|
  config.release '1.2.3'
end
```

**Comment by nateberkopec** [comment]
We guess the `release` intelligently in the following order of preference:

* Heroku's HEROKU_SLUG_COMMIT environment variable
* Reading from the `REVISION` file in the app root (currently only works for Rails, we need to fix this)
* Commit SHA of the last commit (git)

You can set it yourself with the `release` config variable: 

Raven.configure do |config|
  config.release = '1.2.3'
end

**Comment by mllocs** [comment]
:+1:
