### ISSUE TITLE
Specify DNS in capture_exception

### ISSUE THREAD

**Issue by ofelbaum** [getsentry/raven-ruby#455]
Can I specify DNS or project I want to send an exception to?
As I understand SENTRY_DNS is global variable applied to whole application and there is no way to send errors into different Sentry project from the same code.

**Comment by dcramer** [comment]
Take a look at the docs. You can instantiate multiple clients, and the SENTRY_DSN environment variable is simply a shortcut for the default one.

https://docs.getsentry.com/hosted/clients/ruby/
