### ISSUE TITLE
Multiple Raven Instances?

### ISSUE THREAD

**Issue by aryeh-looker** [getsentry/raven-ruby#462]
Is there a way to configure multiple Raven instances? For example: sending a special subset of errors to one DSN and most errors to another DSN.

**Comment by seanlinsley** [comment]
In case there's anything interesting there, I recently built a system to support one or many API authentications for a different project: https://github.com/modernmsg/giftbit/pull/7

**Comment by nateberkopec** [comment]
I think `Raven` is currently set up as a singleton. Maybe @dcramer can weigh in on whether we want to do this - it would make testing a little easier for us I think.

**Comment by dcramer** [comment]
We need to figure out what our story is for this in general. In a lot of larger projects (monorepos) it makes sense to be able to route errors. The solution could be that the individual client can take care of it, but that makes it very complex. The better solution is a "meta client":

```
class MetaClient:
    def send(event):
        this.getClientForEvent(event).send(event)
```

This is a bit awkward, but really what we want is to take advantage of the SDK's ability to inject error handlers, but have the actual processing of data and sending happen in an individual SDK instance that is bound to a single DSN.
