### ISSUE TITLE
`config.catch_debugged_exceptions` in production

### ISSUE THREAD

**Issue by senny** [getsentry/raven-ruby#474]
I was wondering why `config.catch_debugged_exceptions` prevents errors from being reported in production. I assumed that `debugged` is referring to the exception view in the development mode. In reality this also skips exceptions handled by `ActionDispatch::ShowExceptions` which is active in production:

```
RAILS_ENV=production bin/rake middleware | grep ShowExceptions
```

Is it the expected behavior that setting `config.catch_debugged_exceptions = false` will prevent error reports in production?

**Comment by nateberkopec** [comment]
It *is* expected, but you're right - it handles both ShowExceptions and DebugExceptions, which makes the naming confusing. We should probably fix this.

**Comment by senny** [comment]
I think that would be good, It got me confused until I read the code.

**Comment by nateberkopec** [comment]
Reopening until I fix this in the docs
