### ISSUE TITLE
OkJSON doesn't handle large JSON bodies

### ISSUE THREAD

**Issue by brandonjoyce** [getsentry/raven-ruby#481]
We had a JSON message w/ base64 encoded data that it turned out Sentry was locking up on while parsing with the included OkJSON code.  It doesn't error or anything, it just takes a very long time.  (hours) to parse just a ~9mb attachment.  

https://github.com/getsentry/raven-ruby/blob/master/lib/raven/processor/sanitizedata.rb#L75

I'm willing to help w/ this fix, but I want some advice on what direction to go.  Here are a few options I can think of:

- Switch to the built-in ruby json library.  Guessing this is not possible for other reasons, but it does handle the large JSON without a problem.
- Add a default processor to Raven that truncates large json bodies at a limit that's acceptable for OkJSON.  
- Fix OkJSON?  - Not sure how feasible it is to go this route.

**Comment by seanlinsley** [comment]
There's recent conversation on the subject of dropping OkJSON on #480

**Comment by brandonjoyce** [comment]
Very cool.  I think that move to the built-in json library would solve our issue for sure.
