### ISSUE TITLE
Better Transaction Names

### ISSUE THREAD

**Issue by dcramer** [getsentry/raven-ruby#488]
Sentry has the concept of 'culprit' today, but we're likely going to move to a transaction name pattern. I dont think we'll be renaming the attribute as part of this, but the goal will be to provide a native API within clients to override it using a stack approach (see [Python draft](https://github.com/getsentry/raven-python/commit/831b86fa021eceeee74d6b22706c0aca7de73636)).

That is, if you're using Rails, the transaction might be the route name (or the route class that handles it, rather), instead of some semi-arbitrary function in the stacktrace.

Wanted to open this issue to begin discussion on what would fit best there.

For reference, the current culprit that would be replaced shows up similar to ``app/foo.rb in block in blah at line 13``.

**Comment by nateberkopec** [comment]
> That is, if you're using Rails, the transaction might be the route name (or the route class that handles it, rather), instead of some semi-arbitrary function in the stacktrace.

In Rails, we should probably report <controller name>/<action name>.

**Comment by nateberkopec** [comment]
Confirmed that we should be overloading `Culprit` in most integrations

**Comment by nateberkopec** [comment]
Opening a new issue for overhauling integrations
