### ISSUE TITLE
Improve sanitization logic

### ISSUE THREAD

**Issue by dcramer** [getsentry/raven-ruby#489]
Noticed this on a getsentry.com customer, but the "sanitize everything" logic is a bit too aggressive for some situations.

For example, if "secret" is in a filename in the stacktrace, it will get sanitized.

On the server our sanitization logic looks like this:

- sanitize "extra" attribute
- sanitize "vars" in stacktrace (non existant in Ruby)
- sanitize "data", "cookies", "headers", "env", and "query_string" in HTTP data

**Comment by nateberkopec** [comment]
Somewhat related to #485, applying the sanitizer to the stacktraces.

**Comment by nateberkopec** [comment]
Closing as this is similar enough to #485
