### ISSUE TITLE
Raven enables the immutable String feature of Ruby 2.3

### ISSUE THREAD

**Issue by mlammers** [getsentry/raven-ruby#505]
In our application we use a dlog as a logger (https://rubygems.org/gems/dlog/versions/0.2.3).
dlog will force UTF-8 encoding before logging anything. 
Raven uses the frozen String feature of Ruby 2.3, i.e. there is a comment `# frozen_string_literal: true` at the beginning of e.g. the raven/logger. This then throws another error in d_log: `can't modify frozen String`, once Raven tries to log anything.
I am wondering how to approach this. Of course I could try to get rid of dlog, but I'm not sure whether this behaviour of Raven is intentional, since I assume that you'd like to keep it as flexible and unintrusive as possible.
The comment seems to have been added in a commit with Rubocop changes.

Were these changes intentional?

**Comment by nateberkopec** [comment]
The changes were intentional.

I can download `dlog` and try to replicate, but just know this is going to be a "back-burner" issue. `dlog` is clearly doing something unusual, since Raven works just fine with frozen string literals in most other installs.

**Comment by mlammers** [comment]
Alright, thanks a lot for the quick feedback!
I'll close this issue since it was an intentional decision on your side. Just be aware that other Gems might run into similar issues, if they are trying to change immutable Strings passed from Raven.
