### ISSUE TITLE
Raven crashes during rspec, when it is not supposed to be running at all

### ISSUE THREAD

**Issue by pratik60** [getsentry/raven-ruby#513]
We have only configured raven for production and staging, but it seems to be executing the blog even while running tests. 

This was a controller test which was failing, but debugging is hard because this error crops up. In the controller we were attempting to capture exception using Raven and I thought by default it would only happen in the configured environments.

How can we fix this?

/Users/pratikbothra/.rvm/gems/ruby-2.2.2/gems/sentry-raven-1.1.0/lib/raven/utils/deep_merge.rb:10:in `deep_merge!': undefined method `each_pair' for #<RSpec::Mocks::MockExpectationError:0x007fb70acc04c0> (NoMethodError)
	from /Users/pratikbothra/.rvm/gems/ruby-2.2.2/gems/sentry-raven-1.1.0/lib/raven/utils/deep_merge.rb:6:in `deep_merge'
	from /Users/pratikbothra/.rvm/gems/ruby-2.2.2/gems/sentry-raven-1.1.0/lib/raven/event.rb:75:in `from_exception'
	from /Users/pratikbothra/.rvm/gems/ruby-2.2.2/gems/sentry-raven-1.1.0/lib/raven/base.rb:111:in `capture_type'
	from /Users/pratikbothra/.rvm/gems/ruby-2.2.2/gems/sentry-raven-1.1.0/lib/raven/base.rb:256:in `block in install_at_exit_hook'

**Comment by seanlinsley** [comment]
Here's what I do:
```ruby
case Rails.env
when 'production', 'staging'
  require 'raven'

  Raven.configure do |config|
    config.dsn = 'foo'
  end
when 'development', 'test'
  class Raven
    def self.capture_message(*)
    end

    def self.capture_exception(*)
    end

    def self.capture(*)
      yield if block_given?
    end

    def self.user_context(*)
    end
  end
end
```

**Comment by nateberkopec** [comment]
That's intense. I guess we still try to capture exceptions even when the DSN isn't configured. That's kind of dumb, we should just turn off completely.

**Comment by pratik60** [comment]
@seanlinsley That works as a good temp solution. We end up doing something like Raven.capture_exception(e) if Rails.env.staging? || Rails.env.production? etc.

@nateberkopec I agree, it should ideally be turned off completely.
