### ISSUE TITLE
Incorrect stack in chained exception

### ISSUE THREAD

**Issue by dcramer** [getsentry/raven-ruby#514]
Version: 0.15.4

I'm seeing an ActiveRecord::StatementInvalid exception which has two exceptions (chained), but identical stacks in each. This seems to be a bug somewhere in how we're determining what the actual chain is, or we're simply duplicating it (which is equally wrong). 

For internal reference, an example is groupID=136501560 on getsentry.com.

**Comment by nateberkopec** [comment]
Looks like this has been fixed. My repro app shows that only one stack is sent (`null` in the JSON).

[Example JSON](https://gist.github.com/nateberkopec/9954b0d2da26b0b4109e2514297b49b3)
![screen shot 2016-09-16 at 1 47 56 pm](https://cloud.githubusercontent.com/assets/845662/18599174/342451e2-7c14-11e6-8c24-b450555b6b6a.png)
