### ISSUE TITLE
Upgrading to Rails 5 Error

### ISSUE THREAD

**Issue by maclover7** [getsentry/raven-ruby#522]
Hi!

While I was upgrading my application to Rails 5, I got the following error (I am running on `raven-ruby`'s master branch, to make sure that no patches have been applied to fix this error):

```
/home/jon/current/vendor/bundle/ruby/2.2.0/gems/actionpack-5.0.0/lib/action_dispatch/middleware/stack.rb:74:in `insert': can't modify frozen Array (RuntimeError)
	from /home/jon/current/vendor/bundle/ruby/2.2.0/gems/actionpack-5.0.0/lib/action_dispatch/middleware/stack.rb:74:in `insert'
	from /home/jon/current/vendor/bundle/ruby/2.2.0/bundler/gems/raven-ruby-26aaa1f85c5a/lib/raven/integrations/rails.rb:9:in `block in <class:Rails>'
	from /home/jon/current/vendor/bundle/ruby/2.2.0/gems/railties-5.0.0/lib/rails/initializable.rb:30:in `instance_exec'
	from /home/jon/current/vendor/bundle/ruby/2.2.0/gems/railties-5.0.0/lib/rails/initializable.rb:30:in `run'
	from /home/jon/current/vendor/bundle/ruby/2.2.0/gems/railties-5.0.0/lib/rails/initializable.rb:55:in `block in run_initializers'
```

I get this error when running `bundle exec rails test`.

**Comment by maclover7** [comment]
cc @nateberkopec

**Comment by nateberkopec** [comment]
I think I'm going to need a repro app. Can't repro w/"rails new" and our test suite would have caught this anyway.

**Comment by jeremy** [comment]
@maclover7 If you're getting this only when you run your tests, sounds like your app was booted and initialized (and middleware stack frozen) and your test suite is somehow re-initializing the app, possibly in a forked server.

Is that the full backtrace? Can you repro in narrower cases, like running a single test? Do you notice any red flags in how your test suite is set up and run?

**Comment by maclover7** [comment]
Hmm, agree that this is something funky going on with our test suite. Going to close this as an application specific problem.
