### ISSUE TITLE
NameError: uninitialized constant Delayed::Plugins::Raven::Context

### ISSUE THREAD

**Issue by michniewicz** [getsentry/raven-ruby#525]
Hello, guys.
After upgrading from version 1.2.0 to 1.2.1 we are getting the error
     
```
     NameError:
       uninitialized constant Delayed::Plugins::Raven::Context
     # /.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sentry-raven-1.2.1/lib/raven/integrations/delayed_job.rb:46:in `block (2 levels) in <class:Raven>'
```

We think this might be caused by commit https://github.com/getsentry/raven-ruby/commit/bc8988aea7fe01e62b352173b9930ea2e38f1468

**Comment by nateberkopec** [comment]
Pushing 1.2.2 with the fix, thanks for the fast report + PR folks.

**Comment by janraasch** [comment]
Thanks for the fast merge and release 👍
