### ISSUE TITLE
the rest of the API? fetching issues/events etc

### ISSUE THREAD

**Issue by costa** [getsentry/raven-ruby#528]
I wonder if Sentry is planning to add the rest of the API to the gem.

**Comment by nateberkopec** [comment]
There are two APIs - the Server and Client APIs. This gem supports the Client APIs. I'll let @dcramer tell you what the plans are for clients for the Server API.

**Comment by dcramer** [comment]
Unlikely that we'd want the web API here. It's also extremely easy to query against so there's little value in a wrapper.
