### ISSUE TITLE
incompatible with https://github.com/davetron5000/gli

### ISSUE THREAD

**Issue by jlgeering** [getsentry/raven-ruby#531]
```
#!/usr/bin/env ruby
require 'gli'
require 'raven'

include GLI::App

desc 'hello'
command :hello do |c|
	c.action do |global_options,options,args|
		puts "hello"
	end
end

exit run(ARGV)
```

fails with "NoMethodError: private method `desc' called for main:Object"

**Comment by jlgeering** [comment]
see also https://github.com/davetron5000/gli/issues/250

**Comment by jlgeering** [comment]
I don't understand enough ruby magic to know if gli or raven is the culprit

**Comment by davetron5000** [comment]
Raven is doing a lot of stuff, but my guess is that it's somehow bringing in a private method named `desc` into the global namespace.  GLI defined `desc` as public.

You might be able to protected the GLI stuff by using a top-level class:

```ruby

require ''gli"
require "raven"

class MyApp
  extend GLI::App

  # all the GLI stuff you'd normally put at top-level

end

exit MyApp.run(ARGV)
```

If Raven is declaring those methods on `Object`, this might not work, and you might be hosed.  If Raven is just declaring them on wherever you `require`'ed, you have a chance :)

**Comment by dcramer** [comment]
afaict the only use of this is in the rake task

**Comment by jlgeering** [comment]
@davetron5000 yep, wrapping in a class seems to fix it, mucho thanks!
