### ISSUE TITLE
Multiple Slack channels

### ISSUE THREAD

**Issue by Gasparila** [getsentry/raven-ruby#532]
It would be great to send to different slack channels depending on what rule was triggered. For example: an error in onboarding could also be posted to the Sales
slack channel whereas normal errors would only be reported to bugs.

Is there anyway to support this short of creating multiple Sentry projects and sending the exception to each?

**Comment by dcramer** [comment]
Generally wrong issue tracker for core features, but this is something we'll do "one day". Right now its fairly complex, and we dont want to invest time duct taping more stuff onto the existing integrations when we know there's a future better way that we intend to handle alerts.
