### ISSUE TITLE
Log4r Incompatibility with Sentry (1.2.1) and greater

### ISSUE THREAD

**Issue by brentonmorton** [getsentry/raven-ruby#534]
Started to upgrade some applications to Sentry 1.2.1 and found an incompatibility with log4r. 

There was a change made between 1.1.0 and 1.2.1. In ( lib/raven/logger.rb ) that went from:

- 1.1.0 (line: 19) `logger.send(level, "#{LOG_PREFIX}#{msg}") if logger`
- 1.2.1 (line: 29) `logger.add(LEVELS[level], "#{LOG_PREFIX}#{msg}", "sentry") if logger`

The problem with this is there is a bug that log4r has that conflicts with (add).

https://github.com/colbygk/log4r/issues/30

This is valid for Ruby's Logger class (see Logger.add), however for log4r it tries to add an outputter in Log4r::Logger.add

Wondering if you guys know about this already?

**Comment by nateberkopec** [comment]
Did not know, will check it out 👍

**Comment by nateberkopec** [comment]
This is kinda log4r's problem, but the switch to `add` for us was just sort of incidental, so I can switch it back to `send`.

**Comment by brentonmorton** [comment]
Thanks for the fix!
