### ISSUE TITLE
Raven runs runs locally even though configured to run on production only

### ISSUE THREAD

**Issue by kirillzh** [getsentry/raven-ruby#539]
`config/initializers/sentry.rb` initializer:
```ruby
Raven.configure do |config|
  config.environments = %w(production)
  config.tags         = { environment: Rails.env }
end
```

Raven still catches and reports exceptions with `environment` tag `default`.

**Comment by kirillzh** [comment]
Looks like `environments` configuration is ignored when `SENTRY_DSN` is defined.

`SENTRY_DSN` is not defined:
```
D, [2016-09-08T20:57:23.668478 #52950] DEBUG -- sentry: ** [Raven] Don't know how to build task 'blah' (see --tasks) excluded from capture due to environment or should_capture callback
```

`SENTRY_DSN` is defined:
```
D, [2016-09-08T20:43:31.105938 #50860] DEBUG -- sentry: ** [Raven] Sending event e381584257fdb81caae0c2044c246471 to Sentry
D, [2016-09-08T20:43:31.118875 #50860] DEBUG -- sentry: ** [Raven] Raven HTTP Transport connecting to https://app.getsentry.com
```

**Comment by nateberkopec** [comment]
I want to say this is a bug, but we've had this behavior for so long now that I'm sure some people's deployments may be relying on it.

`SENTRY_DSN` is the intended way that you should turn Raven on or off since about version `0.10`. But, if it *overrides* the environment setting, then we should just remove the environment setting altogether. I wonder how this interacts with `config.dsn` as well.

**Comment by nateberkopec** [comment]
NVM, we have tests for this and everything's working as expected - SENTRY_DSN doesnt override environment settings.

Can you repro your problem with [this script](sentryrepro.rb)?

```
$ RAILS_ENV=production SENTRY_DSN=<your_dsn> ruby sentryrepro.rb
...
D, [2016-09-09T12:50:17.601721 #6291] DEBUG -- sentry: ** [Raven] Sending event d333f4b8385f6dea9e4521ee357c815f to Sentry
D, [2016-09-09T12:50:17.606651 #6291] DEBUG -- sentry: ** [Raven] Raven HTTP Transport connecting to https://sentry.io
``` 

```
$ RAILS_ENV=default SENTRY_DSN=<your_dsn> ruby sentryrepro.rb
...
D, [2016-09-09T12:51:05.013368 #6325] DEBUG -- sentry: ** [Raven] divided by 0 excluded from capture due to environment or should_capture callback
```

**Comment by mvz** [comment]
@nateberkopec the link to the script doesn't seem to work.

**Comment by nateberkopec** [comment]
Whoops, correct link: https://gist.github.com/nateberkopec/51e5391f0fb44938ca1c642712cf1ec6

**Comment by nateberkopec** [comment]
Please do reopen if you can reproduce.
