### ISSUE TITLE
Sentry is active before configuration

### ISSUE THREAD

**Issue by mvz** [getsentry/raven-ruby#557]
Hi, I'm in the process of upgrading the dependencies for my app, and when I run `bundle exec rake`, I'm getting an error from webmock that a call to the sentry URL is not stubbed. I have Sentry configured to only send errors in environments 'production' and 'staging'. After digging a little deeper, my preliminary analysis is that the error that is sent occurs before Sentry's configuration, which means the `enviroments` config value is empty, and hence Sentry attempts to send the error.

Is it possible to make Sentry only be active after configuring?

**Comment by mvz** [comment]
As a workaround, I have added `require: false` to the line in the Gemfile for sentry-raven, and added `require 'sentry-raven'` in the sentry initializer file.

**Comment by nateberkopec** [comment]
I'm guessing that since this is Webmock related, this is the `test` environment, right?

**Comment by nateberkopec** [comment]
Accidental close, my b.

**Comment by nateberkopec** [comment]
Also, I'm guessing your Rake default task (what happens when you `bundle exec rake`) is run your tests?

**Comment by mvz** [comment]
Yes, both guesses are correct.

**Comment by nateberkopec** [comment]
There's not too much we can do about errors happening *prior* to your environment configuration, since we don't control Rails' initialization order.

You must be setting the SENTRY_DSN env variable for Sentry to want to try to capture and send. Make sure it isn't set in the test environment, and you'll be fine.

**Comment by nateberkopec** [comment]
Also, I should point out your workaround leaves you blind to errors prior to the Sentry initializer being loaded in production - probably not a big deal because an error before that point probably means your server is down.

**Comment by mvz** [comment]
Thanks, @nateberkopec. I'll see about not setting SENTRY_DSN in the test environment.
