### ISSUE TITLE
Give info what configuration is missing to capture errors

### ISSUE THREAD

**Issue by clupprich** [getsentry/raven-ruby#568]
When the Raven client starts up it emits a log line staging `Raven xxx configured not to capture errors`.

I was too excited to follow the instructions when signing up on sentry.io, so I missed the `server` configuration. Would it be helpful to state the reason for not capturing errors (like: "no server configured" or "environment not listed")? If yes, I'm happy to contribute a PR!

**Comment by nateberkopec** [comment]
@clupprich Absolutely!

**Comment by nateberkopec** [comment]
Closed by #602 - this will be release in 2.2.0 very soon.
