### ISSUE TITLE
request to follow SemVer/update README

### ISSUE THREAD

**Issue by pravi** [getsentry/raven-ruby#581]
Do you follow SemVer.org? If yes, can you mention it in readme? If not can you consider it.

I maintain gitlab package in debian. Apps like gitlab declares a tight dependency like ~> 2.0.0 currently, if they have confidence about minor versions not breaking api, they can instead do ~> 2.0. This will allow debian to ship the latest minor version in a series without breaking gitlab requirement or maintaining a patch to relax the requirement.

**Comment by dentarg** [comment]
Another example is the (SemVer) breaking change "Culprits -> Transactions" from https://github.com/getsentry/raven-ruby/commit/b51883b95ef2ba4743ae3192a7bc20aab07a982d introduced in 2.7.0.
