### ISSUE TITLE
browser and OS reporting incorrect with 2.1.x

### ISSUE THREAD

**Issue by dentarg** [getsentry/raven-ruby#583]
I just switched a Sinatra application running on Heroku from using sentry-raven 1.2.2 to using sentry-raven 2.1.2 and now Sentry doesn't get the browser and OS versions correct, see this screenshot. The oldest event was created when the application was using sentry-raven 1.2.2.

![screen shot 2016-11-10 at 18 35 00](https://cloud.githubusercontent.com/assets/42626/20187418/7c6a4098-a774-11e6-9f8f-0512c698a72a.png)

Related to https://github.com/getsentry/raven-ruby/pull/560?

Please tell if you need more information on this

**Comment by nateberkopec** [comment]
@dentarg Sorry about that. Can you show me the code you're using to add browser/device/os context?

**Comment by dentarg** [comment]
I have no custom code for that, just "use Raven::Rack" in config.ru. Isn't that enough?

**Comment by StephaneRob** [comment]
Same pb with Rails

**Comment by dentarg** [comment]
@nateberkopec any ideas?

**Comment by nateberkopec** [comment]
Will take a look and fix this today 👍

**Comment by nateberkopec** [comment]
It looks like I misunderstood the docs for clients on this issue. If you just pass `os`, Sentry assumes that's the *browser's* OS context, not the context of the server.

**Comment by nateberkopec** [comment]
Fixed in 2.1.3.

Sorry about this. Basically I misunderstood the Sentry client docs. :( We still report server information, but now do so in the proper place.

**Comment by StephaneRob** [comment]
thx @nateberkopec

**Comment by dentarg** [comment]
@nateberkopec thanks for the fix, but I don't really get why sentry-raven isn't reporting browser and OS anymore, see the first event at, it was created with sentry-raven 1.2.2 – it got both the browser and OS correct, I guess it took the info from the User-Agent header? why isn't sentry-raven 2.1 doing that?

![image](https://cloud.githubusercontent.com/assets/42626/20385292/3308709e-acb7-11e6-970b-6b0fba05027e.png)

**Comment by nateberkopec** [comment]
@dentarg Dammit, yup I'm seeing the same. Investigating.

**Comment by nateberkopec** [comment]
Something that I did is messing with the browser/OS auto-detection plugin in Sentry core. Trying to fix this ASAP but the Python people need to look at it and tell me where I'm messing up.

**Comment by nateberkopec** [comment]
Sorry about the confusion here. Difficult to debug behavior that's actually happening on the server end rather than in the client. 

So the actual fix was to move the context out of `contexts` and into `extra`. This is only temporary, watch the linked Sentry core issue for the permanent solution.

This fix is available in 2.1.4, which should be available by the time you read this.

**Comment by dentarg** [comment]
Thanks! It now works as expected again:

![screen shot 2016-11-18 at 23 42 17](https://cloud.githubusercontent.com/assets/42626/20449299/bc259686-ade8-11e6-9241-5620538e9ab6.png)

**Comment by StephaneRob** [comment]
Thx @nateberkopec
