### ISSUE TITLE
Noisy in development/test

### ISSUE THREAD

**Issue by vemv** [getsentry/raven-ruby#607]
Despite I don't set a dsn in test/development environments, and don't even call `Raven.configure` in these environments, I do get a lot of Raven messages which do nothing but distract me.

Examples:

* `Raven 2.1.4 configured not to capture errors.`
* `<error message> excluded from capture due to environment or should_capture callback`

How to entirely silence Raven logging for test/development?

Cheers - Victor

**Comment by vemv** [comment]
`config.logger = Logger.new("/dev/null")` did the trick.

You might want to add this as default behavior!

**Comment by nateberkopec** [comment]
Hmmm, I'll think about silencing logging when the DSN is not configured at all.

**Comment by nateberkopec** [comment]
This won't make it into 2.2, but for now, you can simply provide a different logger (as you've done) or change the logger level.

**Comment by edariedl** [comment]
I have a same trouble with noisy logging in raven gem.

I would expect it to not logging these kinds of things if I am outside the allowed environments.
