### ISSUE TITLE
Warning when running rake tasks in Sinatra 

### ISSUE THREAD

**Issue by tamoyal** [getsentry/raven-ruby#611]
When I run my `rake test` task in a Sinatra app, I get this warning:
`WARN -- sentry: ** [Raven] Unable to load raven/integrations/rake: undefined method 'desc' for Sinatra::Application:Class`

I have yet to enable Sentry in the project (gem is installed because I'll enable it quite soon).

My Rakefile looks like this:
```
require "rake/testtask"

Rake::TestTask.new do |t|
  t.pattern = "spec/**/*_spec.rb"
  t.warning = false
end
```

**Comment by nateberkopec** [comment]
What versions of rake and Sinatra are you using? You can check with ``$ bundle list | grep rake``.

**Comment by tamoyal** [comment]
```
rake (12.0.0)
 sinatra (1.4.7)
```

**Comment by nateberkopec** [comment]
Hey @zzak - this is because Sinatra attaches to the global namespace right? [Are we doing something wrong here](https://github.com/getsentry/raven-ruby/blob/master/lib/raven/integrations/rake.rb) or does @tamoyal have to `require` Sinatra differently (`sinatra/base` or whatever?)

**Comment by nateberkopec** [comment]
@tamoyal Is this a modular-style Sinatra app? If so, can you try `gem "sinatra", require: 'sinatra/base'` in your gemfile?

**Comment by tamoyal** [comment]
@nateberkopec Yep it's modular, yep that solves it, unfortunately surfaces an issue in one of my tests that has to do with using `Rack::Test::UploadedFile.new(fp, 'image/jpeg')` which is super weird but I'm sure there's a great reason for it. I guess I'll have to dig in and say your suggestion does in fact solve the issue?

**Comment by nateberkopec** [comment]
Closing this because it's not a raven-ruby issue IMO, though I'm eager to hear from @zzak if there's anything we can do to alleviate the issue on our end.
