### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by jpawlyn** [getsentry/raven-ruby#615]
Hi. Am currently having problems with logging in version 2.2.0 following this [commit](https://github.com/getsentry/raven-ruby/commit/7bd144e7f69a48072847827d2ae1ff9eb1afe7c0#diff-33932c9449f8123cd79c5592994e2118). 

Previously a logger could be setup in an initializer as shown [here](https://github.com/getsentry/raven-ruby/issues/124#issuecomment-22588881). Any help much appreciated. 

Thanks, Jolyon

**Comment by nateberkopec** [comment]
Can you explain what doesn't work anymore? For example:

```ruby
Raven.configure do |config|
  config.logger = ::Logger.new(STDOUT)
end
```

...logs correctly.

**Comment by jpawlyn** [comment]
Apologies. In our raven initializer we were not calling the raven configuration for certain environments. With the gem update, logging started appearing for these environments, but when I followed the example in the README (`config.environments = %w[staging production]`), the problem was resolved. Sorry!
