### ISSUE TITLE
Reports that large exception messages still being generated/crashing stuff

### ISSUE THREAD

**Issue by nateberkopec** [getsentry/raven-ruby#618]
Have to figure out what code path could possibly be causing this.

**Comment by mrhead** [comment]
@nateberkopec Is this the same thing as https://github.com/getsentry/raven-ruby/issues/642?

I can't figure it out from the issue title :).

**Comment by nateberkopec** [comment]
@mrhead Not really. This report manifested as not being able to send to the Sentry server, not blowing up databases, as in your report.

**Comment by mrhead** [comment]
Got it!
