### ISSUE TITLE
JRuby 9000 paths for files in jars do not parse properly

### ISSUE THREAD

**Issue by the-michael-toy** [getsentry/raven-ruby#620]
When we moved to JRuby 9.1.5.0 sentry stopped working.

Tracked it down to pathnames, in 9000 for ruby running from a jar, pathnames are of the form `uri:classloader:/PATH` which the regex for parsing backtraces didn't handle.

I have a PR ( #619 ) which is what we are using now.

**Comment by nateberkopec** [comment]
Closed by #619
