### ISSUE TITLE
SentryJob in Rails 5 + DelayedJob does not work as in README

### ISSUE THREAD

**Issue by dv** [getsentry/raven-ruby#626]
```ruby
config.async = lambda { |event|
  SentryJob.perform_later(event.to_hash)
}
```

Trying to enqueue a job using the `event.to_hash` as given here, means at some point a Time is tried to be serialized.

This raises the error:
```
Unsupported argument type: Time
/app/vendor/bundle/ruby/2.3.0/gems/activejob-5.0.0.1/lib/active_job/arguments.rb:83:in `serialize_argument'
/app/vendor/bundle/ruby/2.3.0/gems/activejob-5.0.0.1/lib/active_job/arguments.rb:116:in `block in serialize_hash'
/app/vendor/bundle/ruby/2.3.0/gems/activejob-5.0.0.1/lib/active_job/arguments.rb:115:in `each'
# ...
```

It seems to be because of a part of the hash that looks as follows:
```
{:id=>1, :priority=>0, :attempts=>6, :run_at=>Mon, 23 Jan 2017 19:30:38 UTC +00:00, :locked_at=>nil, :locked_by=>nil, :queue=>"mailers", :created_at=>Mon, 23 Jan 2017 18:51:54 UTC +00:00}
```

**Comment by nateberkopec** [comment]
@dv which version of sentry-raven are you running? As of 2.0, `event` is already a JSON-compatible Hash which should be compatible with ActiveJob.

**Comment by dv** [comment]
@nateberkopec thanks for your response. Checked it out, seems I'm still at `1.1.0`, so that would explain it. I updated, thanks for the suggestion!
