### ISSUE TITLE
Exceptions from wrapped ActiveJob Sidekiq jobs lacking context

### ISSUE THREAD

**Issue by vindvaki** [getsentry/raven-ruby#630]
After upgrading `raven-ruby` from an ancient version to the latest version, the only context we get for exceptions raised by workers is `Sidekiq`, greatly reducing the usefulness the list view (lots of errors look the same). Basically, all our worker errors are generic stuff like:

<img width="434" alt="screen shot 2017-01-31 at 16 30 26" src="https://cloud.githubusercontent.com/assets/80280/22471464/add13a6c-e7d2-11e6-9170-e6a3618510d2.png">

whereas before we used to have the file name of the template where the exception was raised.

I've been digging around and it seems like https://github.com/getsentry/raven-ruby/blob/master/lib/raven/integrations/sidekiq.rb#L48 might be missing the case of wrapped jobs, in which case

```ruby
context["job"]["wrapped"]
```

contains at least the job class name (in this case `MailJob`), which would already be a huge improvement over simply `Sidekiq`.

**Comment by nateberkopec** [comment]
TIL what wrapped jobs are! Thanks, I'll add it.

**Comment by nateberkopec** [comment]
^^^ closed on master
