### ISSUE TITLE
How to pass extra data to capture_exception?

### ISSUE THREAD

**Issue by 9mm** [getsentry/raven-ruby#631]
I have read the docs but I don't fully understand how to include data all in a single event request to Sentry.

I want to include the response as extra data in my `capture_exception` call, how might I do this?

```ruby
def process_card
  resp = @client.api_step_1
  # ... do work with response ...
rescue => e
  # ... here is where I want to include 'resp' in capture_exception call
  Raven.capture_exception(e)
  render json: ['There was an error'], status: 422
end
```

**Comment by nateberkopec** [comment]
Sentry calls this "context". See generic explanation here: https://docs.sentry.io/learn/context/

Ruby-specific explanation here: https://docs.sentry.io/clients/ruby/context/
