### ISSUE TITLE
Improve in_app detection

### ISSUE THREAD

**Issue by dcramer** [getsentry/raven-ruby#64]
Currently it marks all frames as in application in many conditions.

For example, one app their entire code has absolute paths that are all like /app/foo/XXX/...

The solution is likely to add in a source root configuration option, and when that is set prepend the app detect with that path.

(We should also remove the absolute detection in in_app, and only check for relative app/* etc paths)

**Comment by nateberkopec** [comment]
I'm pretty satisfied with this behavior r/n.
