### ISSUE TITLE
 What is the best place to put code for additional context in Rails? 

### ISSUE THREAD

**Issue by knzudgt** [getsentry/raven-ruby#648]
I am new to Sentry and still reading the documentation. Apart from adding the gem and getting the basics from Sentry, I would like to add to my Ruby on Rails application the code to create additional request context in the events, as explained in [docs.sentry.io](https://docs.sentry.io/clients/ruby/context/).
In particular, I am interested in using the user_context method to get information about the user experiencing the issue (user's details, browser etc).
Where would you suggest to add the code? In the Application controller? Somewhere else?
Any suggestion from experienced users would be appreciated.

**Comment by nateberkopec** [comment]
@knzudgt Context is cleared after each web response. So, it's usually best to set the context as soon as possible during a web request - usually a `before_filter` works well.

```ruby
class ApplicationController < ActionController::Base
  before_action :set_sentry_context
 
  private
 
  def set_sentry_context
    #example, make sure current_user is set before calling of course
    Raven.user_context(id: current_user.id, email: current_user.email)
  end
end
```
