### ISSUE TITLE
Add explicit stack support

### ISSUE THREAD

**Issue by dcramer** [getsentry/raven-ruby#66]
In Python we allow you to say "stack=True" on any capture method to pull down the current stacktrace.

It looks like Ruby supports this as well, and it'd be a useful addition:

http://stackoverflow.com/questions/11122233/get-current-stack-trace-in-ruby-without-raising-an-exception

**Comment by nateberkopec** [comment]
It doesn't make any sense to add this to capture_exception, right?

**Comment by dcramer** [comment]
@nateberkopec probably not assuming exceptions have stacks always bound to them

**Comment by nateberkopec** [comment]
Closed by #304
