### ISSUE TITLE
custom processors aren't executed in test environments

### ISSUE THREAD

**Issue by Mysrt** [getsentry/raven-ruby#660]
makes it really difficult to write a useful test or know that the code is actually working at all when there is no way to call sentry and have it actually use a processor in a testing environment.

**Comment by nateberkopec** [comment]
Can you expand more on this? Processors don't really vary between environments. 

What you're probably looking for is the dummy transport:

```ruby
require 'raven/transports/dummy'

Raven.configure do |config|
  config.dsn = "dummy://12345:67890@sentry.localdomain:3000/sentry/42"
end
```
