### ISSUE TITLE
Proxy server configuration

### ISSUE THREAD

**Issue by edjames** [getsentry/raven-ruby#663]
Hello. 

I'm trying to find out whether there is support for configuring a proxy server. So far I cannot find any docs that would suggest this is supported, but I have found this:

https://github.com/getsentry/raven-ruby/blob/85ef2ea3c2e9c98c1df3941deab1976018a7a9e7/lib/raven/transports/http.rb#L58

https://github.com/getsentry/raven-ruby/blob/4b0659e859e8c74139fa6ccc82daf62833dddfb4/lib/raven/configuration.rb#L74

https://github.com/getsentry/raven-ruby/blob/3df5025c8ee286c0c9958a93afa9ae3fe5b93672/lib/raven/event.rb#L292

It _looks_ like all I need to do is something like this:

```
Raven.configure do |config|
  config.proxy = 'http://path.to.my.proxy.com'
end
```

Is this all I need to do to configure a proxy?

Thanks.

**Comment by nateberkopec** [comment]
That's correct. I'm leaving this issue open so that I'm reminded to add this to the documentation.

**Comment by edjames** [comment]
Thanks Nate, appreciate the quick response.
