### ISSUE TITLE
Faraday exception rescue does not work with older versions of Faraday

### ISSUE THREAD

**Issue by Zoetermeer** [getsentry/raven-ruby#664]
The gemspec gives a version range for Faraday here: https://github.com/getsentry/raven-ruby/blob/master/sentry-raven.gemspec#L19

However, Faraday < 0.9.0 has `Faraday::Error::ClientError` and this was moved to `Faraday::ClientError` only in that version and higher.  My application current pins at Faraday v0.8.11 and Sentry request failures blow up with

`Uninitialized constant `Faraday::ClientError`.

**Comment by nateberkopec** [comment]
Hm. What's pinning your bundle at 0.8?

**Comment by nateberkopec** [comment]
Well, since both versions inherit from Faraday::Error this is a simple fix.
