### ISSUE TITLE
Partially clear breadcrumb buffer?

### ISSUE THREAD

**Issue by halostatue** [getsentry/raven-ruby#669]
I’ve got a set of importers that are tight loops. I’d like to record breadcrumb information for the items being processed, but clear them on the next loop. This might be something like:

```ruby
def process(row)
  Raven.breadcrumbs.mark
  …
  Raven.breadcrumbs.record do |crumb|
    …
  end
  …
rescue
  exception_thrown = true
  raise
ensure
  Raven.breadcrumbs.release unless exception_thrown
end
```

`#mark` and `#release` might be implemented something like (assume `@marks = []` in `#initialize`).

```ruby
def mark
  @marks.push(@buffer.last) unless @buffer.last.nil?
end

def release
  return if @marks.empty?
  mark = @marks.pop
  index = @buffer.rindex(mark) + 1
  if index
    @buffer[index...@buffer.size] = @buffer[index...@buffer.size].map { nil }
  end
end
```

Does this seem generally useful, or am I out in left field with this?

Updated: I’m pretty sure my index was off-by-one because we don’t want to pop the marker element, just everything added *after*.

**Comment by nateberkopec** [comment]
Not super hot on this. What if I just made the Breadcrumb buffer public?

**Comment by halostatue** [comment]
I’ve done some improvements on it since I posted the above sample implementation, and it pretty much does what I want properly now. I’m not really sure I want the buffer to be settable/gettable as what I’m really after doing is sort of having a “tree” of breadcrumbs. So I have something like this:

```
A
B
C (mark)
-- D
-- E
-- F
-- G (release)
H
```

Here’s the module as I’ve implemented it (I have some unit tests):

```ruby
# frozen_string_literal: true

# require 'sentry-raven'

# Provide a mark/release method for removing breadcrumbs.
module Raven::BreadcrumbBuffer::Marks
  def initialize(*)
    super
    @marks = []
  end

  def mark
    if block_given?
      mark
      yield
      release
    else
      @marks.push(@buffer.last) unless @buffer.last.nil?
    end
  end

  def release
    return if @marks.empty?

    mark = @marks.pop
    index = @buffer.rindex(mark) + 1
    size = @buffer.size - index

    @buffer.slice!(index, size)
    @buffer.insert(0, *([ nil ] * size))
  end
end

unless Raven::BreadcrumbBuffer.ancestors.include?(Raven::BreadcrumbBuffer::Marks)
  class Raven::BreadcrumbBuffer # rubocop:disable Style/Documentation
    prepend Raven::BreadcrumbBuffer::Marks
  end
end
```

**Comment by halostatue** [comment]
Here’s the tests that I’ve made (Minitest, not Rspec) that show the basic concepts and how I’m using it.

```ruby
# frozen_string_literal: true

require 'test_helper'
require 'raven/breadcrumbs/marks'

describe Raven::BreadcrumbBuffer::Marks do
  let(:breadcrumbs) { Raven::BreadcrumbBuffer.new }
  let(:buffer) { breadcrumbs.instance_variable_get(:@buffer) }
  let(:marks) { breadcrumbs.instance_variable_get(:@marks) }

  def record_breadcrumb(message)
    breadcrumbs.record { |c| c.message = message }
  end

  it 'marks nil when there are no breadcrumbs' do
    assert_empty marks
    breadcrumbs.mark
    refute_empty marks
  end

  it 'marks something if there are breadcrumbs' do
    record_breadcrumb 'foo'
    breadcrumbs.mark
    refute_empty marks
  end

  it 'clears all appropriate data' do
    breadcrumbs.mark do
      record_breadcrumb 'Inner'
      assert_equal 'Inner', buffer.last.message
    end

    assert buffer.all?(&:nil?)
  end

  it 'maintains the breadcrumb buffer size' do
    record_breadcrumb 'Outer'
    breadcrumbs.mark do
      record_breadcrumb 'Inner'
      assert_equal 100, buffer.size
    end
    assert_equal 100, buffer.size
    assert_equal 'Outer', buffer.last.message
  end
end
```

**Comment by nateberkopec** [comment]
I discussed this internally and we just don't see the wide use case for it right now. Thanks for bringing it up though, happy to come back to this if we get more requests for it.

**Comment by halostatue** [comment]
Fair enough; it is a little specialized. I don’t just need it for importers, though, because I have a couple of places where we want to track all the breadcrumbs that directly lead to an issue, but have a couple of deeper branches for which the breadcrumbs for path A would hide the common breadcrumbs for the issue in path B.

If you make a public API to the contents of the breadcrumb buffer, or even a way to present an *alternative* breadcrumb buffer, I could make an extension gem that basically does everything I’m doing now without (most) of the monkey patching I’m doing now. (The trick would be integrating into the initialization process so that I could set `@marks`, but I could do that with a conditional set of `@marks` as appropriate.)

**Comment by nateberkopec** [comment]
Yeah I agree. Just making the buffer public is an easy way to let people extend it. Will do.
