### ISSUE TITLE
Errors from code called in ActiveJob missing

### ISSUE THREAD

**Issue by januszm** [getsentry/raven-ruby#671]
* Rails 5.0.2
* sentry-raven  2.4

Although errors raised in the `perform` method body are sent to Sentry, like in the example below:

```ruby
class SentryTestJob < ApplicationJob
  queue_as :default

  def perform
    this_code_will_fail_and_report_to_sentry.io
  end
end
```

If errors occur in the code defined a bit deeper in methods defined in other classes, like service objects , they will *not* be reported to sentry.io

```ruby
class SentryTestJob < ApplicationJob
  queue_as :default

  def perform(some_id
    result = SentryTest.new(some_id).call
  end
end
```

But, errors are captured and sent to sentry.io if you wrap the class/method call that produces them in Raven.capture block

This works:
```ruby
...
  def perform(sf_id)
    Raven.capture do
      result = SentryTest.new(some_id).call
    end
  end
```

**Comment by nateberkopec** [comment]
What ActiveJob backend are you using?

**Comment by nateberkopec** [comment]
A better workaround would be:

```ruby
class ApplicationJob < ActiveJob::Base
  around_perform do |job, block|
    Raven.capture { block.call }
  end
end
```

But I do need to know your queue backend before I can repro.

**Comment by januszm** [comment]
@nateberkopec in the case of this example it was just Rails default `async`

**Comment by nateberkopec** [comment]
Wait, I know what's happening. This is probably related to using queue backends which we don't already have an integration for.
