### ISSUE TITLE
NoMethodError: undefined method `host=' for #<Raven::Event:0x0000000d1621e8>

### ISSUE THREAD

**Issue by gingerlime** [getsentry/raven-ruby#678]
I'm seeing this error in my logs a few times ... 

```
Exception: NoMethodError: undefined method `host=' for #<Raven::Event:0x0000000d1621e8>
/var/local/kenhub/kenhub/vendor/bundle/ruby/2.3.0/gems/sentry-raven-2.4.0/lib/raven/event.rb:67:in `public_send'
/var/local/kenhub/kenhub/vendor/bundle/ruby/2.3.0/gems/sentry-raven-2.4.0/lib/raven/event.rb:67:in `block in initialize'
/var/local/kenhub/kenhub/vendor/bundle/ruby/2.3.0/gems/sentry-raven-2.4.0/lib/raven/event.rb:67:in `each_pair'
/var/local/kenhub/kenhub/vendor/bundle/ruby/2.3.0/gems/sentry-raven-2.4.0/lib/raven/event.rb:67:in `initialize'
/var/local/kenhub/kenhub/vendor/bundle/ruby/2.3.0/gems/sentry-raven-2.4.0/lib/raven/event.rb:107:in `new'
/var/local/kenhub/kenhub/vendor/bundle/ruby/2.3.0/gems/sentry-raven-2.4.0/lib/raven/event.rb:107:in `from_exception'
/var/local/kenhub/kenhub/vendor/bundle/ruby/2.3.0/gems/sentry-raven-2.4.0/lib/raven/instance.rb:114:in `capture_type'
```

**Comment by nateberkopec** [comment]
Are you calling `Raven.capture` manually anywhere? 

This looks specific to your usage, so I need more details.

**Comment by gingerlime** [comment]
We use the Semantic Logger [appender](https://github.com/rocketjob/semantic_logger/blob/master/lib/semantic_logger/appender/sentry.rb), which uses `Raven.capture_message` or `Raven.capture_exception`

**Comment by gingerlime** [comment]
Looking at the code, I suspect the problem originates [here](https://github.com/rocketjob/semantic_logger/blob/master/lib/semantic_logger/appender/sentry.rb#L53). The `context` isn't set inside `extra` in the same way it's done below

(I contributed some small fixes to this code, but didn't create the original version. I think I can submit a PR to fix it though)

**Comment by gingerlime** [comment]
I opened an issue on semantic_logger, and I think the problem is there. I think we can close this now. I'll update if I find anything. Sorry for the false alarm, but indirectly I hope it helped spot the issue :)

**Comment by nateberkopec** [comment]
No problem!

**Comment by reidmorrison** [comment]
@nateberkopec would you mind looking at the appender in Semantic Logger and let us know if anything should be changed to better support logging to Raven?
https://github.com/rocketjob/semantic_logger/blob/master/lib/semantic_logger/appender/sentry.rb

@gingerlime created this ticket to track any changes https://github.com/rocketjob/semantic_logger/issues/74
