### ISSUE TITLE
Ignore ActiveJob::DeserializationError by default

### ISSUE THREAD

**Issue by nateberkopec** [getsentry/raven-ruby#701]
See #642. Activejob deserialization errors are pretty common, usually raised when we deleted the record we were going to process in a background job:

```
class PopulateDocsJob < ApplicationJob
  def perform(repo)
    repo.populate_docs!
  end
end
```

However, if you have an async config that looks like:

```
class SentryJob < ApplicationJob
  queue_as :default

  def perform(event)
    Raven.send_event(event)
  end
end
```

and `repo` isn't found, you'll raise ActiveJob::DeserializationError and blow up your Sidekiq instance as we run into an infinite loop.

Since ActiveJob::DeserializationError is basically a NotFound error, we should ignore it by default, just like all the other NotFound errors we ignore by default.

**Comment by mrhead** [comment]
Hmm,  we do not ignore `ActiveRecord::RecordNotFound` in our application. The same goes for `ActiveJob::DeserializationError`. I want to be informed when it happens so I can check what is wrong.

**Comment by nateberkopec** [comment]
@mrhead What do you have `excluded_exceptions` set to in your config, then?

I opened this issue after realizing 99% of the ActiveJob::DeserializationErrors that I see are just from records being deleted between the job being enqueued and the job executing. They're just noise.

**Comment by mrhead** [comment]
To this:

```
config.excluded_exceptions = ["ActionController::RoutingError", "ActionController::BadRequest"]
```

ActiveJob::DeserializationErrors happen also when you schedule a job from a DB transaction and the job is executed before the transaction is committed. While, this is usually harmless because Sidekiq just restarts the job and then it finish successfully, it can be an issue if for whatever reason you set number of retries to 0.

On the other hand I agree that this is just a noise and probably nothing bad happens if these errors get ignored.

**Comment by mrhead** [comment]
I've just received an `ActiveJob::DeserializationError` and I realized that one reason why I care about these errors is that I know when they happen and I can manually clear the Sidekiq queue and/or make sure that these errors don't happen anymore.
