### ISSUE TITLE
Transaction names useless in ActiveJob

### ISSUE THREAD

**Issue by nateberkopec** [getsentry/raven-ruby#702]
They're just Sidekiq/ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper, etc

**Comment by nateberkopec** [comment]
I should say, Sidekiq using ActiveJob.

**Comment by nateberkopec** [comment]
This only affected old Sidekiq < 4.2.3 when using AJ.

**Comment by aldesantis** [comment]
@nateberkopec FYI, this seems to be happening for us on Sidekiq 6.1.2 and sentry-sidekiq 4.1.1. Do you have any advice?

**Comment by st0012** [comment]
@aldesantis can you open a new issue for your case? thanks
