### ISSUE TITLE
Extra context with Sidekiq error handling unsuccessful

### ISSUE THREAD

**Issue by richessler** [getsentry/raven-ruby#707]
I appreciate your consideration, thank you:

This is a question rather than an issue (I believe).  I'm using the Sidekiq integration with my rails app with Sentry and have hit an impasse in regards to extra context for failures.  I haven't been able to successfully use the `#capture` or `#capture_exception` to pass the additional context.   Digging into the integrations for Sidekiq https://github.com/getsentry/raven-ruby/blob/master/lib/raven/integrations/sidekiq.rb#L19 the error handling should include the extra context but it seems to just chomp it.

This very well may be an implementation error on my end, but using the integration with the appropriate version of Sidekiq should default to using Raven::SidekiqErrorHandler, but again - context is lost.

I can give more information, but wanted to put my feelers our there to see if anyone else was experiencing difficulty with Sidekiq extra context being added to Sentry error reporting.

**Comment by nateberkopec** [comment]
Using `capture` and `capture_exception` inside of sidekiq jobs will not automatically get any extra context. We could probably change the integration to do that, though.

The extra context you see in the integration is only added when an exception is raised by a job, not rescued, and is given to the `error_handlers` chain in Sidekiq.

**Comment by richessler** [comment]
@nateberkopec Thank you very much for the quick response. From what I've deduced, it doesn't make sense (for the way that my app is set up) to pass excess information to the worker in sidekiq for contextual purposes. Would you be able to advise on a 'best practice' of sending contextual data to Raven of a sidekiq exception?

**Comment by nateberkopec** [comment]
> From what I've deduced, it doesn't make sense (for the way that my app is set up) to pass excess information to the worker in sidekiq for contextual purposes. Would you be able to advise on a 'best practice' of sending contextual data to Raven of a sidekiq exception?

I don't understand. It doesn't make sense to add context in your Sidekiq worker, but you want me to give you best practice for sending context of a Sidekiq exception?

If you just let the exception bubble up from the worker, Sentry will report that and attach context.
