### ISSUE TITLE
Config to run a callback everytime Raven catches an exception

### ISSUE THREAD

**Issue by AlaRuba** [getsentry/raven-ruby#718]
Hi,

I was wondering if there was a way to globally configure Raven to call a callback exception every time it catches an exception. An example could be that I want to log it in a database.

I couldn't find anything in the docs that would let me set this globally, apologies if it is there.

**Comment by AlaRuba** [comment]
I was hoping there would be a success version of `transport_failure_callback`

**Comment by nateberkopec** [comment]
We don't have anything like that right now. What would you use it for?

**Comment by AlaRuba** [comment]
So I have Sentry set up for my ruby project. I also post to Slack when a Sentry event happens.

However, for cron job tasks, I would like to post it to separate Sentry channel. Is there a way I can configure Sentry to do this?

I was thinking of using the `transport_success_callback` to inspect the environment and see if I'm in a Cron job of not.

**Comment by nateberkopec** [comment]
Yeah, you could just add an integration to your project. On the Sentry server, Project Settings -> Integrations -> Slack.

Let me know if that doesn't fit your use case, but I think most people that want stuff to happen on event creation are better served by an integration.

**Comment by AlaRuba** [comment]
According to this, https://help.sentry.io/hc/en-us/articles/115000154574-Can-I-route-alerts-to-different-Slack-channels-based-on-tags-?_ga=2.111288836.1007162309.1501866856-73523163.1488507409 I can only have one Slack channel per project. Is there a way around that?

**Comment by nateberkopec** [comment]
@AlaRuba Not sure, I would take it up with github.com/getsentry/sentry
