### ISSUE TITLE
Adding context allows only one time use?

### ISSUE THREAD

**Issue by mxmzb** [getsentry/raven-ruby#724]
i am not totally positive about this and i may be doing something wrong, but could it be that calling `Raven.extra_context()` and other context helpers more than once will ignore the added data and only show the data from the last call?

I am seeing this https://github.com/getsentry/raven-ruby/blob/d1eb5002fb364087b63b1b086e601bc0af1a67e7/lib/raven/instance.rb#L196 right now and it's obviously merging, but following this https://github.com/mperham/sidekiq/wiki/Error-Handling#error-handlers any `Raven.extra_context()` calls in my worker code get ignored.

Not sure any more if this is a Sidekiq or Sentry issue or whether I structured my code wrongly.

**Comment by nateberkopec** [comment]
@mxmzb What version of raven-ruby? IIRC we had issues with extra_context inside Sidekiq until 2.6.0, which was fixed in #713.

**Comment by mxmzb** [comment]
it's `sidekiq 5.0.4` and `sentry-raven 2.6.0`

**Comment by nateberkopec** [comment]
I'm gonna need to see some code so we can reproduce, then. [We have tests for Sidekiq context here.](https://github.com/getsentry/raven-ruby/blob/master/spec/raven/integrations/sidekiq_spec.rb#L122)

**Comment by nateberkopec** [comment]
Please feel free to comment with something I can use to reproduce, otherwise I am closing for now.
