### ISSUE TITLE
Add option for ignoring (filtering/excluding) by User-Agent

### ISSUE THREAD

**Issue by AlexWayfer** [getsentry/raven-ruby#727]
Hello!

We have many `404` reports, sent via `raven-ruby`, from `Spider` device.

`device` field generates on Sentry-server, I guess.

And `User-Agent` in these reports looks like `Python-urllib/2.6`, or `WordPress/4.8; http://our.host`.

Can we add ignoring by `User-Agent` in `raven-ruby`? Because Sentry-server doesn't have custom filters by these fields.

I think, it should check by part of String (Regex, maybe). Example:

```ruby
config.excluded_user_agents += ['Python-urllib', 'WordPress']
```

Thanks.

**Comment by nateberkopec** [comment]
Can you add what you want with the `should_capture` config option?

**Comment by AlexWayfer** [comment]
@nateberkopec Yeah, thank you! But something like that ugly…

```ruby
BOT_USER_AGENTS_REGEXP = /
  (#{
    [
      'Python-urllib', 'Other', 'python-requests', 'uCrawlr', 'uCrawler'
    ]
      .map! { |pattern| Regexp.escape(pattern) }.join('|')
  })
/x

# ...

Raven.configure do |config|
  # ...
  config.should_capture = proc do |_event|
    user_agent = Raven::Context.current.rack_env['HTTP_USER_AGENT']
    !BOT_USER_AGENTS_REGEXP.match?(user_agent)
  end
end
```

**Comment by AlexWayfer** [comment]
@nateberkopec Don't want to add a convenient option for this to the gem?

**Comment by nateberkopec** [comment]
Not really, no. We have too many configuration points as it is, and your solution works just as well as ours would. If more people used/wanted this feature, I would consider a convenience function.
