### ISSUE TITLE
error tracking with rails is not working

### ISSUE THREAD

**Issue by shivamkayal** [getsentry/raven-ruby#735]
Gemfile

`gem "sentry-raven"`

application.rb

```
Raven.configure do |config|
   config.dsn = 'dsn url'
end
```

This configuration doesn't seem to work. But when I give explicitly in the code it seems to work.
```
Raven.capture do
      1/0
end
```

**Comment by nateberkopec** [comment]
> This configuration doesn't seem to work.

Can you give some more details as to why you think it doesn't work? What were you expecting to happen?

**Comment by nateberkopec** [comment]
This sounds kind of like #738, but I can't repro that either.
