### ISSUE TITLE
Rescued Exceptions not being sent

### ISSUE THREAD

**Issue by lewisifer** [getsentry/raven-ruby#753]
Hello,

From reading the docs, I get the idea that exceptions would be sent to Sentry regardless of whether they were rescued or not(i.e the middleware would hand it off to Sentry). Is this true? If so, I'm not able to see rescued exceptions getting sent over, and I was wondering if there are certain conditions under which this wouldn't work, and what those are?

Thanks!

**Comment by nateberkopec** [comment]
What do you mean by rescue? Do you mean `rescue_from` in Rails or just `rescue` in Ruby, i.e.:

```ruby
begin
rescue
end
```

**Comment by lewisifer** [comment]
I was referring to the latter, just rescuing within Ruby.

**Comment by nateberkopec** [comment]
It's impossible for us to capture an exception inside a rescue block, because it never bubbles up any further. You have two options: you can re-raise in the rescue block, or use `Raven.capture_exception`:

```ruby
begin
  raise "Uh oh"
rescue Exception => e
  Raven.capture_exception(e)
end

**Comment by lewisifer** [comment]
Good to know, thanks.
