### ISSUE TITLE
You are running on Heroku but haven't enabled Dyno Metadata

### ISSUE THREAD

**Issue by jonhue** [getsentry/raven-ruby#755]
When migrating my database on Heroku I get the following error:

```
W, [2017-08-24T22:22:27.045068 #4]  WARN -- sentry: ** [Raven] You are running on Heroku but haven't enabled Dyno Metadata. For Sentry's release detection to work correctly, please run `heroku labs:enable runtime-dyno-metadata`
W, [2017-08-24T22:22:27.597419 #4]  WARN -- : DEBUG log level not allowed in sandbox mode for security of confidential information. Changing log level to INFO...
rails aborted!
```

I ran the mentioned command nomerous times now, and the issue is still popping up.

**Comment by nateberkopec** [comment]
What is the output of `$ heroku labs --app <app-name>`?

Specifically, do you see `[ ] runtime-dyno-metadata`? Checked or unchecked?

**Comment by jonhue** [comment]
@nateberkopec It's checked!

**Comment by jonhue** [comment]
@nateberkopec Well, it seems like it fixed itself over time :)

**Comment by cesc1989** [comment]
I know this is old and closed but wanted to share what worked for me to silent the warning:

```
$ heroku labs:enable runtime-dyno-metadata --app [APPNAME]
```

**Comment by maatinito** [comment]
Thanks a lot @cesc1989, the --app [APPNAME] saved me :-)
