### ISSUE TITLE
Capture exception as resolved

### ISSUE THREAD

**Issue by jvenezia** [getsentry/raven-ruby#758]
Hi,

Is there a way to capture an exception and mark it directly as resolved?

My use case is that I mute some exceptions that are going to a retry process, but I want to keep track of them silently in Sentry.

Thanks

**Comment by nateberkopec** [comment]
Is `capture_message` a better fit for your use case?

**Comment by jvenezia** [comment]
No really, I would love to keep track of the exception, like I do with `capture_exception`, and just mark it as resolved.

Something like this: `Raven.capture_exception(exception, resolved: true)`

**Comment by nateberkopec** [comment]
This is not possible with the current Sentry API - you can [open an issue at the main Sentry repo](https://github.com/getsentry/sentry) to request this be added.
