### ISSUE TITLE
Ensure configuration in initializer

### ISSUE THREAD

**Issue by allcentury** [getsentry/raven-ruby#759]
### Problem

We'd like to ensure that Raven is configured correctly at boot time (in our case via a rails initializer).  If we wait until the first time we raise an error we run the risk that our container was mounted with the wrong ENV vars and this exception will get missed.

### Current Solution

We're handling this today by exposing a route that sends an error to Sentry on purpose but this is overkill IMO.  I see that the gem validates that [configuration values are present](https://github.com/getsentry/raven-ruby/blob/f4338fb64bb86e1ea58e0863f03223e7650e8607/lib/raven/configuration.rb#L394) but is there a step better we can do here?  A heartbeat check (using creds) to the server or something similar?

I'd love if we our initializer was something like:

```ruby
config/initializers/raven.rb

  Raven.configure do |config|
    config.sanitize_fields = Rails.application.config.filter_parameters.map(&:to_s) + ["file"]
    config.dsn = "some_url"
    config.environments = %w(qa staging sandbox production)
    config.processors -= [Raven::Processor::PostData]
    config.tags = {
      dimension: ENV["DIMENSION"],
      environment: Rails.env,
      service_name: ENV["SERVICE_NAME"],
      service_tag: ENV["SERVICE_TAG"],
    }
    config.transport_failure_callback = lambda { |event|
      Rails.logger.error("Error sending event to sentry: #{event.inspect}")
    }
  end

  Raven.configuration.valid?
```

That last line would raise an error if the client can't communicate successfully with the Sentry server(s).  Thoughts?

**Comment by ehfeng** [comment]
This was raised in [this StackOverflow question](https://stackoverflow.com/questions/46000819/reporting-to-sentry-to-proof-that-its-working-like-on-start-up/46005079?noredirect=1#comment79152364_46005079) as well.

**Comment by nateberkopec** [comment]
Obviously the best way to do this would be a full integration test by sending an actual event to the Sentry server. You can either just do that yourself or open an issue for a "test route" on the main Sentry repo.

From the *client's* perspective, we can tell you when the configuration will *attempt* to send an event to Sentry with `capture_allowed?`:

```ruby
Raven.configuration.capture_allowed?("test message")
Raven.configuration.capture_allowed?(Exception.new("My test exception"))
```
