### ISSUE TITLE
Docs showing unreleased version

### ISSUE THREAD

**Issue by tijmenb** [getsentry/raven-ruby#764]
At the moment there are a few PRs and commits that haven't been released to Rubygems yet. However, the Sentry docs system will [show the unreleased docs from master](https://docs.sentry.io/clients/ruby), which could cause confusion.

A way to solve this is to create a branch `latest-release` every time we push to Rubygems, and add the following to [sentry-docs/.gitmodules](https://github.com/getsentry/sentry-docs/blob/cd51b3e0855438490e8e137f828614392743506e/.gitmodules#L13-L15):

```diff
[submodule "doc-modules/raven-ruby"]
  path = doc-modules/raven-ruby
  url = https://github.com/getsentry/raven-ruby
+ branch = latest-release
```

**Comment by nateberkopec** [comment]
> A way to solve this is to create a branch latest-release every time we push to Rubygems, and add the following to sentry-docs/.gitmodules:

Ah, that's a great idea. Will do.

**Comment by dentarg** [comment]
(This has been reported before in #666, it led to https://github.com/getsentry/sentry-docs/issues/131 being opened)

**Comment by nateberkopec** [comment]
OK, the official line is we're going to do more [marking of version changed/added](http://www.sphinx-doc.org/en/stable/markup/para.html?highlight=distribution) of particular features (even/especially when not yet released).

**Comment by dentarg** [comment]
Shouldn't all unreleased changes be marked as such before closing this? Issue is still present, and other will likely trip over it until properly fixed (I know about it now, I think I will stick to browsing the docs per tag here on GitHub, but just want to help Sentry improve the service for newcomers)

**Comment by nateberkopec** [comment]
@dentarg Well, I'm releasing a new version today so that will also fix the issue 😆

**Comment by dentarg** [comment]
Haha 👍
