### ISSUE TITLE
Make excluded_exceptions look at the exception `cause`

### ISSUE THREAD

**Issue by tijmenb** [getsentry/raven-ruby#765]
When any exception occurs in a template, Rails will raise a `ActionView::Template::Error`:

https://github.com/rails/rails/blob/a0277a974ce881d975b13634bcc7da17bc906844/actionview/lib/action_view/template.rb#L156-L163

These errors aren't filtered out by `excluded_exceptions` because it doesn't look at the `cause` of the error. Which means we get a lot of errors reported that we intended to filter.

We could change this behaviour by changing this:

https://github.com/alphagov/raven-ruby/blob/f4338fb64bb86e1ea58e0863f03223e7650e8607/lib/raven/configuration.rb#L330-L332

Into something like:

```rb
def excluded_exception?(exc)
  excluded_exceptions.any? do |x|
    exception_class = get_exception_class(x)
    exception_class === exc || exception_class === exc.cause
  end
end
```

Before I make a PR, can we think of unintended consequences of a change like this? Are there other reasons to just look at the raised exception?

**Comment by nateberkopec** [comment]
> can we think of unintended consequences of a change like this?

Well it's a major change in which exceptions are captured. I would only do this in the next major. I'll have to think about it.

**Comment by effron** [comment]
Would you be open to a pr implementing something like this, with the behavior being toggled by a new configuration option that defaults to off? That way it wouldn't impact any current users, so I'm hoping that means it wouldn't need to wait for a major version change. Thanks!

**Comment by HazAT** [comment]
Version `2.9.0` has been released containing the PR of @effron 
Thanks ❤️
