### ISSUE TITLE
Help! - Rails request body filled with asterisk? 

### ISSUE THREAD

**Issue by andychong1996** [getsentry/raven-ruby#766]
Hi guys, I'm not sure why the request body is filled with asterisk??

<img width="1014" alt="screen shot 2017-10-04 at 11 51 06 am" src="https://user-images.githubusercontent.com/12697240/31159257-58f10330-a8fa-11e7-9790-663eb71403c7.png">

![screen shot 2017-10-04 at 12 26 32 am](https://user-images.githubusercontent.com/12697240/31159234-3e204d5e-a8fa-11e7-8677-0279ecc94e3d.png)

**Comment by nateberkopec** [comment]
That's the default behavior. [See here](https://github.com/getsentry/raven-ruby#raven-doesnt-report-some-kinds-of-data-by-default)

To stop removal of the request body, remove the PostData processor:

```ruby
Raven.configure do |config|
  config.processors -= [Raven::Processor::PostData]
end
```

[See the 'processors' config option](https://docs.sentry.io/clients/ruby/config/) for more info.
