### ISSUE TITLE
How to sanitize arguments from ActiveJob?

### ISSUE THREAD

**Issue by halostatue** [getsentry/raven-ruby#767]
I need to pass a sensitive parameter from the web to a job, and if an exception gets thrown, I want to make sure that Sentry scrubs that parameter in reporting.

How do I do this?

**Comment by atmos** [comment]
@halostatue We use [rbnacl](https://rubygems.org/gems/rbnacl) to encrypt anything sensitive that we'd send to a job. Specifically the [simplebox](https://github.com/cryptosphere/rbnacl/wiki/SimpleBox) implementation for encrypting/decrypting. It's a lot better than param filtering when it comes to sensitive things.

**Comment by nateberkopec** [comment]
I'll add "How To Write Your Own Processor" to the documentation. But basically, look at the existing processors.
