### ISSUE TITLE
Swallow specified exceptions

### ISSUE THREAD

**Issue by vassilevsky** [getsentry/raven-ruby#768]
Hi 🙂

How bad of an idea is this on a scale of 1 to lack of generics in Go?

```ruby
Raven.configure do |config|
  config.swallow_exceptions = [FooError, BarError]
end
```

Exceptions of these classes are then NOT raised after reporting.

I think it will be useful for non-critical, "good-to-know" exceptions.

**Comment by nateberkopec** [comment]
Hm, can you give a concrete example of a type of exception you would do this with?

My first thought is that swallowing and not re-raising is a concern of the application, not `raven-ruby`.

**Comment by vassilevsky** [comment]
I gave it another thought and concluded that this was a terrible idea indeed. Raven should be absolutely transparent to any application.
