### ISSUE TITLE
Problem with Rails 3.2.x

### ISSUE THREAD

**Issue by selialkile** [getsentry/raven-ruby#785]
I having problem with last version of sentry(2.7.2) and Rails 3.2.
When I run migrations or rails console:

NoMethodError: undefined method `around_action' for ActionController::Base:Class
/.../.rvm/gems/ruby-2.1.5/gems/sentry-raven-2.7.1/lib/raven/integrations/rails/controller_transaction.rb:5:in `included'
/.../.rvm/gems/ruby-2.1.5/gems/sentry-raven-2.7.1/lib/raven/integrations/rails.rb:16:in `include'
/.../.rvm/gems/ruby-2.1.5/gems/sentry-raven-2.7.1/lib/raven/integrations/rails.rb:16:in `block (2 levels) in <class:Rails>'
/.../.rvm/gems/ruby-2.1.5/gems/activesupport-3.2.22.2/lib/active_support/lazy_load_hooks.rb:36:in `instance_eval'
/.../.rvm/gems/ruby-2.1.5/gems/activesupport-3.2.22.2/lib/active_support/lazy_load_hooks.rb:36:in `execute_hook'
/.../.rvm/gems/ruby-2.1.5/gems/activesupport-3.2.22.2/lib/active_support/lazy_load_hooks.rb:26:in `block in on_load'
/.../.rvm/gems/ruby-2.1.5/gems/activesupport-3.2.22.2/lib/active_support/lazy_load_hooks.rb:25:in `each'
/.../.rvm/gems/ruby-2.1.5/gems/activesupport-3.2.22.2/lib/active_support/lazy_load_hooks.rb:25:in `on_load'
/.../.rvm/gems/ruby-2.1.5/gems/sentry-raven-2.7.1/lib/raven/integrations/rails.rb:14:in `block in <class:Rails>'
/.../.rvm/gems/ruby-2.1.5/gems/railties-3.2.22.2/lib/rails/initializable.rb:30:in `instance_exec'
/.../.rvm/gems/ruby-2.1.5/gems/railties-3.2.22.2/lib/rails/initializable.rb:30:in `run'
/.../.rvm/gems/ruby-2.1.5/gems/railties-3.2.22.2/lib/rails/initializable.rb:55:in `block in run_initializers'
/.../.rvm/gems/ruby-2.1.5/gems/railties-3.2.22.2/lib/rails/initializable.rb:54:in `each'
/.../.rvm/gems/ruby-2.1.5/gems/railties-3.2.22.2/lib/rails/initializable.rb:54:in `run_initializers'
/.../.rvm/gems/ruby-2.1.5/gems/railties-3.2.22.2/lib/rails/application.rb:136:in `initialize!'
/.../.rvm/gems/ruby-2.1.5/gems/railties-3.2.22.2/lib/rails/railtie/configurable.rb:30:in `method_missing'
/.../devel/nephelae/config/environment.rb:5:in `<top (required)>'
/.../.rvm/gems/ruby-2.1.5/gems/activesupport-3.2.22.2/lib/active_support/dependencies.rb:251:in `require'
/.../.rvm/gems/ruby-2.1.5/gems/activesupport-3.2.22.2/lib/active_support/dependencies.rb:251:in `block in require'
/.../.rvm/gems/ruby-2.1.5/gems/activesupport-3.2.22.2/lib/active_support/dependencies.rb:236:in `load_dependency'
/.../.rvm/gems/ruby-2.1.5/gems/activesupport-3.2.22.2/lib/active_support/dependencies.rb:251:in `require'
/.../.rvm/gems/ruby-2.1.5/gems/railties-3.2.22.2/lib/rails/application.rb:103:in `require_environment!'
/.../.rvm/gems/ruby-2.1.5/gems/railties-3.2.22.2/lib/rails/application.rb:305:in `block (2 levels) in initialize_tasks'
/.../.rvm/gems/ruby-2.1.5/gems/rake-11.2.2/exe/rake:27:in `<top (required)>'
/.../.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `eval'
/.../.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => db:migrate => environment
(See full trace by running task with --trace)

This occurs after gem 2.7.x of sentry-raven .

**Comment by nateberkopec** [comment]
Sorry, [Rails 3 support was dropped a year ago](https://github.com/getsentry/raven-ruby/commit/a6c75986b9b01f0ed16998e3022b90bd8394be60). I believe v 2.1 and lower are compatible.

**Comment by delphaber** [comment]
@nateberkopec could you please update the documentation ( https://docs.sentry.io/clients/ruby/integrations/rails/ ). It says it's compatible with Rails 3

**Comment by giemsky** [comment]
@nateberkopec You should upgrade you doc then:
`We support Rails 3 and newer.`

https://docs.sentry.io/clients/ruby/integrations/rails/

**Comment by nateberkopec** [comment]
Thanks @giemsky, fixed.

**Comment by bonafernando** [comment]
It worked for me like this:
``` ruby
require 'sentry-raven-without-integrations'
Raven.inject_without(:sidekiq)
Raven.configure do |config|
  config.dsn = ENV["SENTRY_DSN"]
end
```

**Comment by halida** [comment]
Here is my fix: https://github.com/halida/raven-ruby/commit/1910ed9cb7f967e5f3d247c7959fc438c2efe9c7

@selialkile

@nateberkopec old rails project cannot upgrade, I'm not sure this fix can works in all cases.
