### ISSUE TITLE
"Incomplete response received from application" error in production

### ISSUE THREAD

**Issue by vetalpaprotsky** [getsentry/raven-ruby#791]
I use rails 4.1.14.1, ruby 2.0.0-p481 and sentry-raven 2.6.3 in my project. It works perfectly on my local machine. I tested it in development and production environments. But it doesn't want to send the errors to Sentry on "live" production. Instead, I see this message "Incomplete response received from application" from Nginx, each time some error occurs. Locally, I didn't use Nginx. 
In rails logs I see this "Raven::Error - execution expired". So, what I did is I increased the timeout to 10 seconds.
```
Raven.configure do |config|
  config.sanitize_fields = Rails.application.config.filter_parameters.map(&:to_s)
  config.environments = ['staging', 'production']
  config.timeout = 10 # Timeout when waiting for the server to return data in seconds.
  config.open_timeout = 10 # Timeout waiting for the connection to open in seconds.
  if Rails.application.secrets.sentry_dsn.present?
    config.dsn = Rails.application.secrets.sentry_dsn
  end
end
```
It didn't help. I get the same "Incomplete response" error(after waiting 10 seconds). The problem is that I don't have access to the Nginx and I don't know how it is configured. One thing I know is that we use "https" protocol.
When I was testing this gem locally, I used "http". Does it have some impact? I'm just out of ideas what could this be...

**Comment by nateberkopec** [comment]
> When I was testing this gem locally, I used "http"

It is probably some kind of SSL configuration issue. You can try the `rake raven:test` Rake task to see if using the http URL works for you in production. If it does, then it's definitely a problem with TLS/SSL on your server. `$ rake raven:test[DSN_GOES_HERE]`.

**Comment by vetalpaprotsky** [comment]
I've figured it out! I had to use proxy. After I added 
```
config.proxy = 'http://my.proxy'
```
it started working on the live production!
This issue can be closed!
