### ISSUE TITLE
[Sidekiq] Display stringified version of globalid

### ISSUE THREAD

**Issue by louim** [getsentry/raven-ruby#797]
Hey!

I'm not sure if that's the right place to ask, but it would be useful if the Sidekiq context:
https://github.com/getsentry/raven-ruby/blob/14fd97f84f218a8ff16024aadea3430eb1dd169f/lib/raven/integrations/sidekiq.rb#L24
would include the `.to_s` version of globalid when such key is present.

How it currently look:
![capture d ecran 2017-11-21 a 14 53 00](https://user-images.githubusercontent.com/923718/33094084-e40c0fb2-cecc-11e7-8de3-05e7dcdc4b13.png)

That object reference isn't much help when debugging a problem. The original `gid://elite/Contractor/1040` globalid string would be much more useful.

Would that make sense?

**Comment by nateberkopec** [comment]
Yes, that makes sense. Not my top priority but would accept PR 👍
