### ISSUE TITLE
Async event delivery fails to write relevant information to logs

### ISSUE THREAD

**Issue by eanlain** [getsentry/raven-ruby#800]
`Raven::Client.send_event` expects a `Raven::Event`, but when Raven is configured to send asynchronously, the event that Raven passes to the async callback is a JSON-like hash. When `Raven::Client.send_event` is called with the JSON-like hash, the logger fails to correctly access event information.

### Setup

Let's assume that we're using the naive async implementation documented in the README:

```ruby
config.async = lambda { |event|
  Thread.new { Raven.send_event(event) }
}
```

### Sending an Event

Before the async call we have a `Raven::Event`

```ruby
=> #<Raven::Event:0x0000003308da80
 @breadcrumbs=
  #<Raven::BreadcrumbBuffer:0x0000003308da08
   @buffer=
    [nil,
...
 @checksum=nil,
 @configuration=
  #<Raven::Configuration:0x00000017746708
   @async=#<Proc:0x00000017745740@/home/user/my_app/app/sentry/notifier.rb:1 (lambda)>,
   @context_lines=3,
   @current_environment="test",
...
```

When sending an event asynchronously, Raven passes back a JSON-like hash to the configured async callback. 

https://github.com/getsentry/raven-ruby/blob/177d24dbe85e164a9e5a8fc475a1071e871acded/lib/raven/instance.rb#L118-L120

At this point we have a JSON-compatible hash (a hash with string keys):

```ruby
=> {"event_id"=>"2f27070cea8a40428bf9f825f9b58042",
    "timestamp"=>"2017-11-29T16:51:44",
    "time_spent"=>nil,
    "level"=>40,
    "platform"=>"ruby",
    ...
    "message"=>"RuntimeError: purposely raising error"}
```

In our async callback we pass the JSON-like hash that was given to us back to Raven's `send_event` method, which then calls `to_hash`. Raven expects the event to be a `Raven::Event` (as that's what the synchronous implementation passes in) as opposed to a `Hash`. When `to_hash` is called, it's actually the `Hash#to_hash` that's being called as opposed to `Raven::Event#to_hash`.

https://github.com/getsentry/raven-ruby/blob/177d24dbe85e164a9e5a8fc475a1071e871acded/lib/raven/client.rb#L21-L25

No conversion happens and our JSON-like hash remains unaltered. The result of `event.to_hash`:

```ruby
=> {"event_id"=>"2f27070cea8a40428bf9f825f9b58042",
    "timestamp"=>"2017-11-29T16:51:44",
    "time_spent"=>nil,
    "level"=>40,
    "platform"=>"ruby",
    ...
    "message"=>"RuntimeError: purposely raising error"}
```

Raven then tries to log a message, but since our event hash is using string keys as opposed to symbols, the `:event_id` is returned as `nil`.

https://github.com/getsentry/raven-ruby/blob/177d24dbe85e164a9e5a8fc475a1071e871acded/lib/raven/client.rb#L32

The message in our logs reads as:

`"Sending event  to Sentry"`

As opposed to:

`"Sending event c4936371f581494cb87d482f5e075676 to Sentry"`

Additionally, other logger messages after that (e.g. failed send) that try to access values on the event using symbols are missing relevant information:

https://github.com/getsentry/raven-ruby/blob/177d24dbe85e164a9e5a8fc475a1071e871acded/lib/raven/client.rb#L101

`"Failed to submit event: <no message value>"`

**Comment by cantino** [comment]
Does this mean the documentation is wrong to recommend usage of

```ruby
config.async = lambda { |event|
  Thread.new { Raven.send_event(event) }
}
```

?
