### ISSUE TITLE
Support for exceptions with custom attributes

### ISSUE THREAD

**Issue by rdavila** [getsentry/raven-ruby#803]
Given we have the following custom exception:

```ruby
class MyError < StandardError
  attr_reader :action

  def initialize(message, action)
    super(message)

    @action = action
  end
end
```

When a new error is raised:

```ruby
raise MyError.new("Permission Denied", :delete)
```

Looks like Raven is only capturing the message (`Permission Denied`), I'm wondering if is there a way to get access to the values of custom attributes (like `delete` in this case). I've tried to do it through a custom Processor but inside the `def process(data)` method the `data` value is a Hash and doesn't have any reference to the exception object.

**Comment by nateberkopec** [comment]
It's not documented outside of the code, but Exceptions can provide context to an event by [responding to a few different messages.](https://github.com/getsentry/raven-ruby/blob/master/lib/raven/event.rb#L49)
