### ISSUE TITLE
No changelog for 2.7.1

### ISSUE THREAD

**Issue by perlun** [getsentry/raven-ruby#804]
It seems to be missing here: https://github.com/getsentry/raven-ruby/releases

**Comment by nateberkopec** [comment]
Thanks. For the record, the canonical changelog is not the github releases pages, it's `changelog.md`.

**Comment by perlun** [comment]
> Thanks. For the record, the canonical changelog is not the github releases pages, it's changelog.md.

OK, thanks for making that clear. For others reading this, that means this: https://github.com/getsentry/raven-ruby/blob/master/changelog.md
