### ISSUE TITLE
undefined local variable `env` in Rack::Timeout::Request

### ISSUE THREAD

**Issue by mweitzel** [getsentry/raven-ruby#806]
Upon a timeout, I received this error from Raven.
```
NameError: undefined local variable or method `env' for #<Rack::Timeout::RequestTimeoutError:0x007fcc0e47c368>
 8 module RackTimeoutExtensions
 9   def raven_context
10     { :fingerprint => ["{{ default }}", env["REQUEST_URI"]] }
11   end
12 end
```
Not sure if this `env` was supposed to be `ENV` or if if it should have been defined somewhere.

Truncated stack trace
```
[GEM_ROOT]/gems/sentry-raven-2.7.1/lib/raven/integrations/rack-timeout.rb:10 :in `raven_context`
[GEM_ROOT]/gems/sentry-raven-2.7.1/lib/raven/event.rb:64 :in `from_exception`
[GEM_ROOT]/gems/sentry-raven-2.7.1/lib/raven/instance.rb:114 :in `capture_type`
[GEM_ROOT]/gems/sentry-raven-2.7.1/lib/raven/integrations/rack.rb:28 :in `capture_type`
[GEM_ROOT]/gems/sentry-raven-2.7.1/lib/raven/integrations/rack.rb:55 :in `rescue in call`
[GEM_ROOT]/gems/sentry-raven-2.7.1/lib/raven/integrations/rack.rb:50 :in `call`
...
[GEM_ROOT]/gems/puma-2.15.3/lib/puma/configuration.rb:79 :in `call`
[GEM_ROOT]/gems/puma-2.15.3/lib/puma/server.rb:541 :in `handle_request`
[GEM_ROOT]/gems/puma-2.15.3/lib/puma/server.rb:388 :in `process_client`
[GEM_ROOT]/gems/puma-2.15.3/lib/puma/server.rb:270 :in `block in run`
[GEM_ROOT]/gems/puma-2.15.3/lib/puma/thread_pool.rb:106 :in `call`
[GEM_ROOT]/gems/puma-2.15.3/lib/puma/thread_pool.rb:106 :in `block in spawn_thread`
```

---

rails 4.2
puma 2.15.3
sentry-raven 2.7.1
rack 1.6.8
rack-timeout 0.2.0
observed on heroku

**Comment by MeredithAnya** [comment]
@nateberkopec had another person write in about this as well

**Comment by nateberkopec** [comment]
It looks like this extension is only compatible with rack-timeout 0.3.0 or above. rack-timeout 0.2.0 is 3 years old, so you should upgrade. However, I'll look into if there's a quick and easy fix here, and at least turn off the extension if the versions are not compatible.

**Comment by nateberkopec** [comment]
Closed by e13a0c74a9a3c

**Comment by jackdhall** [comment]
Hey @nateberkopec, are there any plans to release a patch version with this fix? I can always point at a `SHA`, but would prefer a version.

**Comment by nateberkopec** [comment]
Yes, I have a few bugfixes I'm working on right now so I'll have a new patch out by Saturday or so.

**Comment by jackdhall** [comment]
Awesome.

Thank you for addressing this bug so quickly.
