### ISSUE TITLE
Error in the sidekiq error handler.

### ISSUE THREAD

**Issue by jjoos** [getsentry/raven-ruby#816]
ruby 2.3.6p384
sidekiq (4.2.5)
sentry-raven (2.7.2)

I'm seeing this error in our logs, indication an error in the error handler preventing them to be sent to sentry:
```
{"severity":"ERROR","message":"!!! ERROR HANDLER THREW AN ERROR !!!","@timestamp":"2018-03-07T09:52:08.423Z","@version":"1"}
{"severity":"ERROR","message":"no member 'wrapped' in struct","@timestamp":"2018-03-07T09:52:08.423Z","@version":"1"}
{"severity":"ERROR","message":"/applications/x/shared/bundle/ruby/2.3.0/gems/sentry-raven-2.7.2/lib/raven/integrations/sidekiq.rb:59:in `[]'\n/applications/x/shared/bundle/ruby/2.3.0/gems/sentry-raven-2.7.2/lib/raven/integrations/sidekiq.rb:59:in 
```

So either `context` or `job` is sometimes a `Struct` ( https://github.com/mperham/sidekiq/blob/2ed92600fa71a9c275189d01df369ad4f8b9ca32/lib/sidekiq/fetch.rb#L10 ) and, therefor trying ta access 'wrapped' or 'class' isn't falsey it throws an error `no member 'x' in struct`. 

We still get errors from sidekiq into sentry so this isn't completely broken, this might be only triggered when we use delayed job like jobs?

https://github.com/getsentry/raven-ruby/blob/master/lib/raven/integrations/sidekiq.rb#L59 
```ruby,name=sidekiq.rb
def transaction_from_context(context)
  classname = (context["wrapped"] || context["class"] ||
                (context[:job] && (context[:job]["wrapped"] || context[:job]["class"]))
              )
```
So we need to change fetching the class name to make sure we don't run into an Struct.

I'm not sure but this could be caused by: #702

**Comment by mperham** [comment]
That’s a sidekiq bug, please upgrade
