### ISSUE TITLE
config.should_capture docs can be more accurate

### ISSUE THREAD

**Issue by dogweather** [getsentry/raven-ruby#827]
The docs state that [the proc is given an "Event"](https://docs.sentry.io/clients/ruby/config/). But it's not an `Event`. Rather, it's [a String or an Exception](https://github.com/getsentry/raven-ruby/blob/master/lib/raven/configuration.rb#L129-L133). This imprecision sent me down a wrong path — fairly frustrating.

**Comment by nateberkopec** [comment]
Sorry about that. That doc wasn't intended to convey the type of the argument, but I can definitely see how it implied that. Fixed.
