### ISSUE TITLE
Cannot send to Raven over Proxy without new gem release 

### ISSUE THREAD

**Issue by halostatue** [getsentry/raven-ruby#829]
We’re currently using Raven 2.7.2 which does not work (output of `rake raven:test`).

```
-> Unable to record event with remote Sentry server (NoMethodError - undefined method `[]' for #<URI::HTTP https://xx.yyy.zzz.aaa:bbbb>):
```

When I manually applied the changes in #820 to my bundled Raven, I was able to successfully send an error.

Please release a new version of the gem (2.7.3) ASAP because this is blocking a production release.

**Comment by nateberkopec** [comment]
Fixed: https://github.com/getsentry/raven-ruby/releases/tag/v2.7.3

**Comment by halostatue** [comment]
Thanks! Our packages for release were built yesterday, so we’ll pop up to 2.7.3 with the next release.
