### ISSUE TITLE
Raven::Rack middleware not loaded

### ISSUE THREAD

**Issue by janklimo** [getsentry/raven-ruby#834]
Using a Rails 4 app, today I found out that `Raven::Rack` middleware is not present in the middleware list.

I'm loading the gem as `gem 'sentry-raven', '~> 2.7.3', require: 'sentry-raven-without-integrations'` and then calling `Raven.inject_without(:sidekiq)` in the initializer.

I believe what's happening here is that railtie is required _after_ the Rails app is initialized, so none of the `initializer`s in `raven/integrations/rails.rb` will be run.

This spec then is a false positive
https://github.com/getsentry/raven-ruby/blob/1be277bb2fcb651fca0f1018bf9f3e5dc55077cc/spec/raven/integrations/rails_spec.rb#L12-L14

since the railtie is always required before the app is initialized:
https://github.com/getsentry/raven-ruby/blob/6a2c99d9b16df04f8a6a728f0824397b6617c2c5/spec/support/test_rails_app/app.rb#L10

which is not the case when going the `sentry-raven-without-integrations` + `inject_without` route.

I've verified that `before-` and `after-initialize` are still run:
https://github.com/getsentry/raven-ruby/blob/1f32429de3e7ce8219da92d804248e0493c4feed/lib/raven/integrations/rails.rb#L37-L61

**Comment by cedricpim** [comment]
I can confirm this. I am encountering the same problem.

Was anyone able to find a workaround?

**Comment by sheki** [comment]
We are seeing this too with the 2.7.4 version of the gem

**Comment by agis** [comment]
We bumped onto this yesterday. A workaround is to do `Sentry.inject(:sidekiq)` inside `config/application.rb`.

**Comment by cedricpim** [comment]
I ended up finding that the issue was another dependency that was loading ActiveSupport in its initializer. 

However, it is still a shame that you can't just disable ActiveJob and need to disable everything else.

**Comment by st0012** [comment]
@janklimo is this still an issue to you after upgrading to `3.0`+ versions?

**Comment by janklimo** [comment]
Sorry @st0012 not using Sentry with `inject_without` anymore (that was an old project) so can't really add to this.

**Comment by st0012** [comment]
ok thanks, I'm closing this for now then. If anyone sees this issue and still encounter it, you can ping me and I'll reopen it.
