### ISSUE TITLE
Sanitize only sanitizes integers not decimals, despite being valid JSON

### ISSUE THREAD

**Issue by tlabeeuw** [getsentry/raven-ruby#852]
The following test case fails:

```ruby
  it 'sanitizes decimals' do
    data = {
      "secret" => -123.432
    }

    result = @processor.process(data)

    expect(result["secret"]).to eq(Raven::Processor::SanitizeData::INT_MASK)
  end
```

Since a ruby `Decimal` is a valid [JSONNumber](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON) the above example should work! This applies to other times of `Numeric` like `BigDecimal`.

Similarly booleans are also not sanitized, but this would be harder. Maybe `BOOL_MASK = false`, or alternatively just use the `STRING_MASK`.

**Comment by nateberkopec** [comment]
> the above example should work

I mean, it is called `Raven::Processor::SanitizeData::INT_MASK` for a reason 😆 

SanitizeData is only intended to catch credit card numbers. Matching floats and booleans is out-of-scope, you should write your own processor for what you need *or* match on the key, not the value.

**Comment by tlabeeuw** [comment]
@nateberkopec In that case I would suggest changing the [documentation](https://docs.sentry.io/clients/ruby/config/) and or name of the `sanitize_fields` param (maybe `sanitize_string_fields` and `sanitize_integer_fields`). Seems artificially restrictive, to only sanitize some types of values but others.

**Comment by nateberkopec** [comment]
That's reasonable. https://github.com/getsentry/sentry-docs/pull/341 fixes.

We can't sanitize types other than Integer and String because a) it would be extremely slow and b) will inevitably break when people put strange types into the sanitizer.
