### ISSUE TITLE
Configurable Rack environment formatting 

### ISSUE THREAD

**Issue by 0xdiba** [getsentry/raven-ruby#854]
It would be really useful if the `ENVIRONMENT` desired fields for rack env could be set through a config or an env variable. ( The allowed environment fields for rack are currently hardcoded [here](https://github.com/getsentry/raven-ruby/blob/master/lib/raven/integrations/rack.rb#L131) )

If an empty formatter is provided, all fields in the environment hash are to be recorded.

**Comment by agis** [comment]
Hey, any updates on this one?

**Comment by st0012** [comment]
Closed by https://github.com/getsentry/raven-ruby/pull/860
