### ISSUE TITLE
Does sentry-raven still need the secret in the DSN env var?

### ISSUE THREAD

**Issue by UsmannK** [getsentry/raven-ruby#866]
On my projects' settings pages on sentry.io I see the following:

> DSN (Deprecated)
> This DSN includes the secret which is no longer required by Sentry' newer versions of SDKs. If you are unsure which to use, follow installation instructions for your language.

The README for raven-ruby is still using this format. Is that correct?

**Comment by nateberkopec** [comment]
Support was added in #847 and [released in 2.7.4](https://github.com/getsentry/raven-ruby/blob/master/changelog.md#274).

I've also added some tests to verify here: 8cf89bff28df55d700855777c862b3efba754ba6

**Comment by nateberkopec** [comment]
Thanks also for pointing out that the README used the old format. I've fixed that as well: 8e5f33c4e9f95cdaa638887752910820babbd670

**Comment by pboling** [comment]
Based on my testing in practice this is not the case.  I was not able to use the new DSN on 2.7.4.

**Comment by hawkins** [comment]
> # Or you can configure the client in the code (not recommended - keep your DSN secret!)

@nateberkopec , you updated the readme, but the comment above still indicates that the DSN should be kept secret, even though it now only discloses a public key and project ID. I'm a new sentry customer and can't find this answer in the documentation anywhere on the website - is the DSN still unsafe to share in client code (i.e., client-only Ruby apps), despite not embedding a client *secret* in the DSN anymore?

**Comment by pboling** [comment]
@getsentry @nateberkopec Is this going to be fixed?
