### ISSUE TITLE
How to send release?

### ISSUE THREAD

**Issue by GaboFDC** [getsentry/raven-ruby#873]
Other implementations have the option to set the release.
```python
sentry_sdk.init(release="my-project-name@2.3.12")
```
```js
Sentry.init({
  release: "my-project-name@2.3.12"
})
``` 

I haven't found in the documentation anywhere who to do it in ruby/rails

**Comment by blairanderson** [comment]
I would also like to know this, i've not been able to find in the code either.

**Comment by blairanderson** [comment]
it looks likes EVENTS that are sent will pull the current release from the configuration https://github.com/getsentry/raven-ruby/blob/master/lib/raven/event.rb#L198 

but i am not sure if this is the same as sending an init event with release data

**Comment by dentarg** [comment]
Just dropping a permalink for the above URL https://github.com/getsentry/raven-ruby/blob/v2.7.4/lib/raven/event.rb#L198 as the "master link" will probably point to some other line of code in the future :)

**Comment by jeremy** [comment]
You can use `sentry-cli` to manage releases: https://docs.sentry.io/cli/releases/

Note that the config doesn't create a release using Sentry API. It sets the release to use for Sentry events. That's autodetected, but you can manually override with
```ruby
Raven.configure do |config|
  config.release = '2.3.12'
end
```

**Comment by blairanderson** [comment]
Using the CLI requires another dependency and onboarding Too many people. Are there other ways to achieve?

Blair

**Comment by DanRoestorf** [comment]
When using the Raven config in this manner:
```
Raven.configure do |config|
  config.release = ENV['RELEASE']
end
```

What is the best value to use as RELEASE? I see in the documentation for Ruby specifically it mentions a commit sha, but other docs it shows a `app@1.0.0` syntax.

I'd prefer to use my git tag for the release. Do I gain anything by passing in a commit SHA?

**Comment by agis** [comment]
As of 2.9.0, the release is (mostly) automatically retrieved from git:

https://github.com/getsentry/raven-ruby/blob/729c22f9284939695f14822683bff1a0b72502bd/lib/raven/configuration.rb#L220

**Comment by dentarg** [comment]
Is this correct? `detect_release` is only doing the "Tell Sentry When You Deploy a Release" step from https://docs.sentry.io/workflow/releases/, I still need to use the Sentry API somewhere in my deploy process to do the "Associate Commits with a Release" step

**Comment by agis** [comment]
AFAICT this is a separate step and is done by using the web API and not from raven-ruby.

**Comment by alexanderadam** [comment]
The process of registering a release [seems to be simple though](https://blog.sentry.io/2017/05/09/release-deploys#shell-script-example).
It should be doable without a dependency (unless the logic changed nowadays).

By the way, there's also [PR 910](https://github.com/getsentry/raven-ruby/pull/910/files) which seems to add support for setting the release as ENV variable in general.

**Comment by st0012** [comment]
As @jeremy said, you should be able to set the release with

```ruby
Raven.configure do |config|
  config.release = "revision"
end
```

If it's not set, the SDK will detect release from different sources in the following order:
1. `ENV["SENTRY_CURRENT_ENV"]`
2. git
3. capistrano revision file or `revisions.log`
4. `ENV["HEROKU_SLUG_COMMIT"]` if your app is on heroku

I'm going to close this now, but feel free to reopen it if you still have questions on release detection 😄

**Comment by alexanderadam** [comment]
@st0012 there's still no support for [_creating_ release information](https://docs.sentry.io/workflow/releases/?platform=browser#using-the-api), right?

**Comment by st0012** [comment]
currently, we have no plan to support creating release information from SDK (not just Ruby SDK, but all SDKs). so please use either the API or cli for that purpose as the document suggests. I'll keep you posted if this decision was changed 😄
