### ISSUE TITLE
`::Raven::Configuration#capture_in_current_environment?` doesn't respect environment whitelist

### ISSUE THREAD

**Issue by thesmart** [getsentry/raven-ruby#874]
There is a bug in `Raven::Configuration` that prevents disabling Raven using the environment whitelists.

```rb
# disable raven for all environments
::Raven.configure do |config|
  config.environments = [] # enable in zero environments
end
# ... snip
def capture_in_current_environment?
  # this next line can't evaluate to false
  return true unless environments.any? && !environments.include?(current_environment)
  @errors << "Not configured to send/capture in environment '#{current_environment}'"
  false
end
```

This line is wrong:
https://github.com/getsentry/raven-ruby/blob/c622003ee6406b0f1d32ae1dd2e75e5be88d0402/lib/raven/configuration.rb#L383

Should be:
```rb
return true if environments.any? && environments.include?(current_environment)
```

Simple test case:
```
environments = []
current_environment = 'production'
puts 'should not print' unless environments.any? && !environments.include?(current_environment) 
puts 'fix will not print' if environments.any? && environments.include?(current_environment)
```
prints
```
should not print

```

**Comment by galtzo** [comment]
This is because the empty array means "enable in all environments".
And that is because the default setting should be "on".
To keep the default setting as on, and allow for a blank whitelist to mean off, they would have to default to using a whitelist of your actual environment names, but different projects have different environment names, so it's unrealistic.

A solution you could use:
```
# Empty environments is equivalent to *all* environments
config.environments = %w[ production staging ]
if ENV["DISABLE_SENTRY"] == "true"
  Rails.logger.warn("Turned off Sentry for local #{Rails.env}")
  config.environments -= [ Rails.env.to_s ]
end
```

**Comment by st0012** [comment]
As @galtzo explained, this is because the SDK is designed to be `on` in at least 1 environment. Closing this now.
