### ISSUE TITLE
Provide mechanism to retrieve DSN from configuration

### ISSUE THREAD

**Issue by thomas-mcdonald** [getsentry/raven-ruby#877]
We run Sentry against a few Rails applications. It would be nice if there was a helper method on `Raven::Configuration` that would allow retrieval of the set DSN so we can use it when setting up the frontend reporter.

Right now we can grab `Raven.configuration.release` and render it in the view but have to reconstruct the URL (or copy over from our config). My proposal would mean that instead of

```
Raven.config('url reconstruction / copy from config}', {
          release: "#{Raven.configuration.release}"
        }).install()
```

you could have something a bit more standard like

```
Raven.config('Raven.configuration.dsn}', {
          release: "#{Raven.configuration.release}"
        }).install()
```

**Comment by tmikoss** [comment]
Would love to see this implemented. My use case is setting up JS client for frontend error reporting as well. 

Currently fetching `ENV['SENTRY_DSN']` value. That works, but will silently break frontend error reporting, if that particular ENV variable is no longer used.

**Comment by st0012** [comment]
sorry for the long waiting, I've added https://github.com/getsentry/raven-ruby/pull/1012 for this
