### ISSUE TITLE
When the $CHILD_STATUS is nil but the result is not raise an error.

### ISSUE THREAD

**Issue by ggrocco** [getsentry/raven-ruby#878]
https://github.com/getsentry/raven-ruby/blob/62ee180b2ec9618397ca6ec52a11485244950dac/lib/raven/base.rb#L102

<img width="646" alt="screen shot 2018-11-27 at 2 07 18 pm" src="https://user-images.githubusercontent.com/95619/49094601-c5383980-f24d-11e8-81e3-f1fb2dc7fc7b.png">

**Scenario**: I have one Sidekiq running inside a Kubernetes cluster, before I kill the process we send an event to Sidekiq to stop, `bundle exec sidekiqctl stop $PID`. Then this error show on Sentry.

**Comment by st0012** [comment]
this has been fixed in https://github.com/getsentry/raven-ruby/commit/302ca391b006c286500a6afe53da26987005b625
