### ISSUE TITLE
Rails files marked as in_app in stacktrace

### ISSUE THREAD

**Issue by KieranP** [getsentry/raven-ruby#892]
I have a rails app, deployed via capistrano to /home/web/apps/production, so has the following paths:
* /home/web/apps/production/current
* /home/web/apps/production/releases
* /home/web/apps/production/shared

You end up with files like:
* /home/web/apps/production/releases/20190225105938/app/services/mobile_services/push.rb
* /home/web/apps/production/shared/bundle/ruby/2.3.0/gems/delayed_job-4.1.5/lib/delayed/command.rb

The issue I'm facing is that when the backtrace is parsed, the /home/web part is being removed for some reason (I haven't figured out why yet). So the paths ends up being:

* apps/production/releases/20190225105938/app/services/mobile_services/push.rb
* apps/production/shared/bundle/ruby/2.3.0/gems/delayed_job-4.1.5/lib/delayed/command.rb

Because the regexp for paths makes the root path optional (https://github.com/getsentry/raven-ruby/blob/master/lib/raven/backtrace.rb#L78), the regexp ends up being just the APP_DIRS_PATTERN (https://github.com/getsentry/raven-ruby/blob/master/lib/raven/backtrace.rb#L87), which matches the above lines.

```
Regexp.new("^(bin|exe|app|config|lib|test)")
```

So all backtrace lines are arriving at Sentry with in_app set to true, making it very difficult to easily scan a backtrace for where the problem actually lies.

**Comment by KieranP** [comment]
Further info upon digging further, this only seems to affect exceptions caught in delayed_job processing. Exceptions caught within web requests have the proper files mark as in_app. So something to do with how exceptions are generated in delayed_job is stripping the /home/web root folder, causing issues.

**Comment by KieranP** [comment]
Seem to have fixed it by changing the APP_DIRS_PATTERN via the following:

```
config.app_dirs_pattern = /(app|bin|config|db|lib|script|spec)\//
```

**Comment by st0012** [comment]
@KieranP I'm glad that you've found a solution 😄 Therefore, I'm closing this issue now 😉
