### ISSUE TITLE
Setting server_name in raven config doesn't do anything

### ISSUE THREAD

**Issue by bbugh** [getsentry/raven-ruby#896]
Hi there! If we try to set the `server_name` on the configuration, it doesn't do anything. Looking at the code, there is a `server_name` setting (like the other platforms), but the server name setting doesn't show up in the sentry issues.

```ruby
Raven.configure do |config|
  config.server_name = Figaro.env.HEROKU_APP_NAME
end
```

**Comment by st0012** [comment]
@bbugh thanks for reporting, what's the version are you using? In `3.0.0` this config seems to work fine.

**Comment by st0012** [comment]
Closing this now. but feel free to reopen it if you still see this issue in the newer versions 😄
