### ISSUE TITLE
SENTRY_CURRENT_ENV vs. SENTRY_ENVIRONMENT

### ISSUE THREAD

**Issue by mfb** [getsentry/raven-ruby#901]
Confusingly some of the other Sentry SDKs support a SENTRY_ENVIRONMENT env variable, but raven-ruby supports SENTRY_CURRENT_ENV.

**Comment by coorasse** [comment]
Stumbled upon that as well and had to go through the code to understand what was the issue. We should support also SENTRY_ENVIRONMENT. I'll open a PR
