### ISSUE TITLE
NoMethodError: undefined method `byteslice' for []:Array

### ISSUE THREAD

**Issue by ericproulx** [getsentry/raven-ruby#907]
Hello,

Sidekiq integrations calls `Raven.capture_exception` like this:
```ruby
 Raven.capture_exception(
        ex,
        :message => ex.message,
        :extra => { :sidekiq => context }
      )
```

Unfortunately, if `ex.message` isn't a String (in our case, it was a Hash), it fails with ```NoMethodError: undefined method `byteslice' for []:Array```

I know it's weird that `ex.message` isn't a String, but it works when calling it like this :
```ruby
# ex is an exception
Raven.capture_exception(ex)
```

When looking at code, `event.message` is interpolated properly only if `Raven.capture_exception` wasn't call with options `message`
```ruby
# lib/raven/event.rb

def self.from_exception(exc, options = {}, &block)
      ...
      new(options) do |evt|
        evt.message = "#{exc.class}: #{exc.message}" # interpolated properly

        evt.add_exception_interface(exc)

        yield evt if block
      end
    end
```

Is it a bug ? I don't know, but I had to `to_s` my value before raising an exception.

Thanks

**Comment by st0012** [comment]
I think it doesn't make much sense to accept a non-string `message`. However, as a error-reporting SDK it shouldn't cause any new error when taking non-string input. I will open a PR for this.
