### ISSUE TITLE
Exclude exceptions based on class and message?

### ISSUE THREAD

**Issue by kaspergrubbe** [getsentry/raven-ruby#912]
With Honeybadger we can exclude exception like this:

```ruby
Honeybadger.exception_filter do |notice|
  exc = notice[:exception]
  (Net::SMTPServerBusy === exc && exc.message == "401 4.1.3 Bad recipient address syntax") ||
  (Errno::ENETUNREACH  === exc && exc.message.to_s.include?("freegeoip.net"))
end
```

Is there any way to achieve the same with Raven-ruby?

**Comment by st0012** [comment]
Currently, we only support excluding exceptions with their classes. We'll consider adding this feature in the future though 😄
