### ISSUE TITLE
Disabled environment still checks for DSN

### ISSUE THREAD

**Issue by alex-benoit** [getsentry/raven-ruby#915]
`Raven 2.XX.0 configured not to capture errors: DSN not set` keeps showing in development event thought the environment is disabled using `config.environments = %w[production]`

I would expect the `config.environments` to be the source of truth on enabled/disabled environments, and this should be checked before the DSN.

Is this the intended behaviour?

**Comment by gamesover** [comment]
quite true.

It still reports below at `development` env
```
Raven 2.11.0 configured not to capture errors: DSN not set
```

Though my config
```ruby
Raven.configure do |config|
  config.environments = %w(staging production)
  config.sanitize_fields = Rails.application.config.filter_parameters.map(&:to_s)
end
```

**Comment by wooly** [comment]
I'm finding this as well. It looks like this has come up before (#607, #793) and the best workaround so far is to set the logger to `/dev/null`

**Comment by alexanderadam** [comment]
I explained once [why this is clearly buggy behaviour](https://github.com/getsentry/raven-ruby/issues/793#issuecomment-507616423) but I didn't get any answer so far.

**Comment by pond** [comment]
Yeah also followed up on surprisingly-was-closed #793 - agree with comments here - workarounds like logger to `dev/null` are IMHO hacks which although they might work, shouldn't be needed.

**Comment by timdorr** [comment]
For anyone running into this, here is a workaround:

```rb
raven_environments = %w[staging production]

Raven.configure do |config|
  config.silence_ready = !raven_environments.include?(Rails.env)
  config.environments = raven_environments
end
```

Nonetheless, I agree that ignoring unspecified environments should be the default behavior.

**Comment by st0012** [comment]
Thanks for reporting, this issue should be fixed by https://github.com/getsentry/raven-ruby/pull/1000
