### ISSUE TITLE
does raven support auth tokens?

### ISSUE THREAD

**Issue by chicks-net** [getsentry/raven-ruby#921]
According to the [sentry docs](https://docs.sentry.io/api/auth/): 

> API keys are a legacy means of authenticating. They will still be supported but are disabled for new accounts. You should use authentication tokens wherever possible.

When I try to specify a URL with `token@localsentry/project` I get an error:

```
I, [2019-09-26T19:05:18.553131 #30111]  INFO -- sentry: ** [Raven] Raven 2.6.3 configured not to capture errors: No secret_key specified
```

Is there a way to get Raven to support auth tokens?  Or how can I generate a keypairs in Sentry 8.21 that work with Raven?

**Comment by karlwilbur** [comment]
I realize that this is several months old, but wanted to provide at least some kind of help.

Older versions of the Raven gem (anything prior to v2.7.4) require a password in the URI but new accounts do not get a URI with a password. 

Compare v2.6.3 (the version shown in your error message):
https://github.com/getsentry/raven-ruby/blob/v2.6.3/lib/raven/configuration.rb#L215-L220

...against v2.13.0 (the newest 2.x version as of this date):
https://github.com/getsentry/raven-ruby/blob/v2.13.0/lib/raven/configuration.rb#L242-L247

A simple solution is to just add a bogus password. Somethings like:
```ruby
# Actual DSN
config.dsn = "https://0123456789abcdef0123456789abcdef@acb123.ingest.sentry.io/0000000"

# DSN with bogus password
config.dsn = "https://0123456789abcdef0123456789abcdef:NIL@acb123.ingest.sentry.io/0000000"
```

The recommended fix would be up to upgrade Raven to a newer version, one which is both compatible with your app and which supports a "passwordless" DSN. This is not always possible.

**Comment by st0012** [comment]
@karlwilbur thanks for the answer! 
@chicks-net I'm closing this for now. Feel free to reopen it if this is still an issue after upgrading to a newer version (`3.0.0` is recommended).
