### ISSUE TITLE
Raven.extra_context no longer returns tags (regression in v2.12.0)

### ISSUE THREAD

**Issue by matt-thomson** [getsentry/raven-ruby#931]
Previously, the return value from `Raven.extra_context` was the set of tags that were in the context.  However, since #920, this method now returns nil.

**Comment by rivayama** [comment]
Created a PR to fix this issue https://github.com/getsentry/raven-ruby/pull/933, sorry for the inconvenience 🙇

**Comment by rivayama** [comment]
The fix has got merged and then released in [v2.12.2](https://github.com/getsentry/raven-ruby/releases/tag/v2.12.2) 🙏

**Comment by matt-thomson** [comment]
Many thanks @rivayama! This is working for us.
