### ISSUE TITLE
Allow faraday 1.0

### ISSUE THREAD

**Issue by connorshea** [getsentry/raven-ruby#944]
Faraday 1.0.0 came out a few days ago, but sentry-raven doesn't allow it in the gemspec.

I tried making a PR, but there are a handful of test failures with faraday 1.0.0 and I'm not sure how to fix them.

https://github.com/lostisland/faraday/blob/e346b8bdb46ee7f38ee5f9d519ad227a14de9612/CHANGELOG.md#v10

**Comment by ksylvest** [comment]
PR: https://github.com/getsentry/raven-ruby/pulls

**Comment by tanelsuurhans** [comment]
We are running into this as well, `twilio-ruby` sets Faraday to `~> 1.0.0`, which bumps `sentry-raven` down to `1.x`, which in turn causes errors when we queue up Sentry errors, which in turn just crashed our Redis server with about 1.6M recursively queued and failing errors in Sidekiq :)

So yeah it would be cool to get this bumped maybe.

**Comment by scottbartell** [comment]
I think @ksylvest meant to link to: https://github.com/getsentry/raven-ruby/pull/946

**Comment by ksylvest** [comment]
^ I did - 🤦‍♂️

**Comment by ksylvest** [comment]
Can this be closed now? https://github.com/getsentry/raven-ruby/pull/946 got merged (although un-released).

**Comment by kjanoudi** [comment]
Can we release?

**Comment by tsrivishnu** [comment]
Can this be release soon? Dependancy conflicts with `Elasticsearch` gem `v7.4.0`. Elasticsearch required Faraday 1.0.0

**Comment by ksylvest** [comment]
Looks like it is live! https://rubygems.org/gems/sentry-raven/versions/3.0.0 !

**Comment by st0012** [comment]
Since version 3.0.0 has allowed faraday 1.0.0, I'm closing this now 😉
