### ISSUE TITLE
Ungroupable error stacktraces: can Raven-Ruby leverage `Rails.backtrace_cleaner`?

### ISSUE THREAD

**Issue by davidstosik** [getsentry/raven-ruby#957]
Switching to Sentry 10 recently, we started having big issues with error grouping in our Rails application. It didn't take us long to notice that the problem seems to come form same errors having different stacktraces.

The difference is located in the name of methods generated from template files.
I couldn't find better documentation or Rails code extracts, so instead allow me to share this RailsConf video extract instead 😬: [_templates are translated into methods_](https://youtu.be/8Dld5kFWGCc?t=2359).

The stacktrace would look something like that:
![image](https://user-images.githubusercontent.com/816901/80476016-c0b50a80-8984-11ea-90c4-b21f92f4828b.png)

Focus on `_app_views_home_index_html_erb___2412767935268124114_70177239986900`. This method name is generated from the `app/views/home/index.html.erb` template. I could not pinpoint in Rails code where those strings of digits (fingerprints?) are generated and appended to the method name, but they seem to vary depending on multiple factors (at least the file's content, but it looks like for a given file we've produced multiple values). This generated in Sentry multiple errors that would not be grouped together.

Here's what a stacktrace diff looks like between two errors I would expect to get grouped together on Sentry, but that did not:

<img src="https://user-images.githubusercontent.com/816901/80477490-f8bd4d00-8986-11ea-8197-ee9a226cbc26.png" width="300" />

This diff was displayed in Sentry's "Similar issues" tab.

There might be settings on Sentry that would allow those similar issues to eventually look close enough to be merged by Sentry, but I wondered what tools were available on my end to clean that up.

That's when I found about [ActiveSupport::BacktraceCleaner](http://api.rubyonrails.org/classes/ActiveSupport/BacktraceCleaner.html). This is what Rails uses to display cleaner, more focused backtraces when an error is displayed.

In fact, [Rails::BacktraceCleaner](https://github.com/rails/rails/blob/b66235d432d0505857ff667e0a1ddecfb5640a56/railties/lib/rails/backtrace_cleaner.rb#L19) introduces a filter that cleans up the template method names from the backtrace, which is exactly what I was looking for. It also removes a lot of noise which is not really what we're looking for when first debugging the application on Sentry. (Silencers are what splits the "application trace" from the "framework trace".)

I though it would be great if I could just apply `Rails.backtrace_cleaner` to the stack traces before they get sent to Sentry, but the best thing I found myself able to do (without rewriting that logic), was to write a small monkey patch. 🙈 

```rb
module Raven
  class Backtrace
    class << self
      alias_method :orig_parse, :parse
      def parse(backtrace, opts = {})
        orig_parse(::Rails.backtrace_cleaner.clean(backtrace), opts)
      end
    end
  end
end
```

I hijacked the `Raven::Backtrace.parse` method in order to clean up the backtrace while it's still a raw array of lines, before Raven works on it and produces frames it will send to Sentry. The result, for the same error I screenshot at the top, can be seen in this other screenshot:
![image](https://user-images.githubusercontent.com/816901/80478865-20adb000-8989-11ea-951a-b3fe0f8b6c47.png)

That's quite satisfying, and should fix our problems with errors not getting merged together (also should help making the stacktrace displayed on Sentry more workable, by [focusing](https://github.com/rails/rails/blob/0196551e6039ca864d1eee1e01819fcae12c1dc9/activesupport/lib/active_support/backtrace_cleaner.rb#L4-L8) on the parts of the code that are most likely to be producing errors.

Now the part I'm not satisfied about, obviously, is that I had to write a monkey patch. 🐒

My question is: is there any better mechanism (provided by Raven, or else) that would allow an application to apply a `BacktraceCleaner` to the raw backtrace before it gets parsed by Raven? (I am aware of Raven's processors, but those happen _after_ the stacktrace has been parsed...)

**Comment by bblack** [comment]
@davidstosik a question unrelated to your issue, but related to your screenshot: 

Do you know why Sentry's web app sometimes shows multiple similar errors in a single group? In your screenshot, for example, is shown two different errors, with two different classes: An `ActionView::Template::Error` and a `NameError`. I've got a project where this has caused hundreds of different groups to appear in Sentry's web app, where the only difference is the number of such errors displayed in one group, and I cannot figure out whether that's a bug in Sentry's web app, a but in Sentry's client lib, a bug in our application, or everything working as intended and I just can't figure out what that intent is.

**Comment by st0012** [comment]
@davidstosik thanks for reporting! I think this is an issue that needs to be solved. But using Rails' backtrace_cleaner directly is too risky as they're pretty aggressive and behave quite differently in different Rails versions.

Anyway, I've created #1011 to solve this issue in the least impactful way.
