### ISSUE TITLE
Is 3.0.0 missing fixes and improvements form v3?

### ISSUE THREAD

**Issue by davidstosik** [getsentry/raven-ruby#962]
Hello.

Browsing ruby-raven's code, issues, and commit history, to find details around [`IGNORE_DEFAULT`](https://github.com/getsentry/raven-ruby/blob/master/lib/raven/configuration.rb#L175), I found this PR: https://github.com/getsentry/raven-ruby/pull/769

As you can see, it was merged to a branch named `v3`. Unfortunately, it looks like that branch never got anywhere, and the improvement got lost...
Are there any plans to port whatever good bits are left in `v3` to a future version of raven-ruby, or is that lost unless someone opens a new PR for it?

**Comment by st0012** [comment]
hi @davidstosik, I'm the new maintainer of this SDK and we do plan to pick some of the fixes/features from the v3 branch in the future. PR #769 is definitely one of them as well.

**Comment by st0012** [comment]
It's been merged into the `v3-1` branch now
